### PR TITLE
move  metrics  from common to dubbo-metrics

### PR DESCRIPTION
**Pull request by wxbty**
## What is the purpose of the change

The content of metrics should not be placed in the common package

## Brief changelog

move  to dubbo-metrics，add a separate dubbo-metrics-default package,  dubbo-metrics-api only needs interfaces and javabeans

### CODE REVIEW

**Comment by AlbumenJ** [comment]
@songxiaosheng PTAL

**Comment by songxiaosheng** [comment]
@wxbty 
Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.metrics.service.MetricsServiceExporter by name default, no related exception was found, please check whether related SPI module is missing.
	at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:760)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:767)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:561)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:535)
	at org.apache.dubbo.common.extension.ExtensionLoader.getDefaultExtension(ExtensionLoader.java:587)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initMetricsService(DefaultApplicationDeployer.java:356)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initialize(DefaultApplicationDeployer.java:212)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.start(DefaultApplicationDeployer.java:611)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:226)
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:215)
	at com.apache.dubbo.demo.graalvm.consumer.Application.runWithBootstrap(Application.java:68)
	at com.apache.dubbo.demo.graalvm.consumer.Application.main(Application.java:40)
Error: Process completed with exit code 1.

**Comment by wxbty** [comment]
> @wxbty Exception in thread "main" java.lang.IllegalStateException: No such extension org.apache.dubbo.metrics.service.MetricsServiceExporter by name default, no related exception was found, please check whether related SPI module is missing. at org.apache.dubbo.common.extension.ExtensionLoader.findException(ExtensionLoader.java:760) at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:767) at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:561) at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:535) at org.apache.dubbo.common.extension.ExtensionLoader.getDefaultExtension(ExtensionLoader.java:587) at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initMetricsService(DefaultApplicationDeployer.java:356) at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initialize(DefaultApplicationDeployer.java:212) at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.start(DefaultApplicationDeployer.java:611) at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:226) at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:215) at com.apache.dubbo.demo.graalvm.consumer.Application.runWithBootstrap(Application.java:68) at com.apache.dubbo.demo.graalvm.consumer.Application.main(Application.java:40) Error: Process completed with exit code 1.

done

**Review by songxiaosheng — APPROVED** [review]
LGTM

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
image

Please fix conflicts

**Comment by AlbumenJ** [comment]
image

**Comment by wxbty** [comment]
> pull_request

done,  there is another ci [ubuntu-latest] failure, no reason can be seen

**Review by songxiaosheng — APPROVED** [review]
LGTM

**Review by songxiaosheng — APPROVED** [review]
LGTM

**Review by AlbumenJ — APPROVED** [review]

**Pull request merged**
