### PR TITLE
[Dubbo-4716] Fix judgment ipv4 address

### PR DESCRIPTION
**Pull request by complone**
## What is the purpose of the change

XXXXX

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by htynkn** [comment]
Could you please provide some detail for this PR?

**Comment by complone** [comment]
> Could you please provide some detail for this PR?

Hello,These two commits are

- fix ipv4 address judgment error in order to solve [#4716](https://github.com/apache/dubbo/issues/4716) issue

- fix the classloader of the MetadataReportService used by Class.forName in the [#4712](https://github.com/apache/dubbo/issues/4712) issue, so try to build a classLoader to pass to the thread context, but I don't know why the check failed.

**Comment by tswstarplanet** [comment]
Your repository seems not clean. Please follow the steps in CONTRIBUTING.md

**Comment by complone** [comment]
> Your repository seems not clean. Please follow the steps in CONTRIBUTING.md



> Your repository seems not clean. Please follow the steps in CONTRIBUTING.md

@tswstarplanet 
Hello, I have emptied the extra files

**Comment by tswstarplanet** [comment]
LGTM

**Pull request merged**
