### PR TITLE
[Dubbo-4918]Check deploy environment when invoke dubbo service using telnet

### LINKED ISSUE #4918: Check deploy environment when invoke dubbo service by telnet
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

For the sake of security, invoking dubbo service by telnet should only be allowed when application is deployed in dev or test environment.

### PR DESCRIPTION
**Pull request by tswstarplanet**
## What is the purpose of the change

fix #4918

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by tswstarplanet** [comment]
I think invoking dubbo service by telnet in production environment is of high risk. So we should limit telnet invoke by environment.
And the invoke field of ProtocolConfig actually doesn't work because it's not used in current edition.

**Comment by kexianjun** [comment]
> instead of using environment to disable telnet, should we use explicit flag? We may need to consider to disable telnet completely in com.alibaba.dubbo.remoting.exchange.support.ExchangeHandlerDispatcher.
> 
> In fact com.alibaba.dubbo.config.ProtocolConfig has setTelnet() method, which can be used to enable explicit command.
> 
> What do you think?

agree, and the telnet config has already been supporte.see the following page's description about telnet ,we can config which telnet commands are enabled http://dubbo.apache.org/zh-cn/docs/user/references/xml/dubbo-protocol.html

**Comment by tswstarplanet** [comment]
> http://dubbo.apache.org/zh-cn/docs/user/references/xml/dubbo-protocol.html

I test it, whether set telnet or not of ProtocolConfig, the telnet is available.

**Comment by beiwei30** [comment]
> > http://dubbo.apache.org/zh-cn/docs/user/references/xml/dubbo-protocol.html
> 
> I test it, whether set telnet or not of ProtocolConfig, the telnet is available.

@tswstarplanet I think we should focus on investigating why ProtocolConfig's set doesn't work, instead of introducing a new flag, what do you think?

**Pull request closed without merging**
