### PR TITLE
Refactor  metrics data Composite

### PR DESCRIPTION
**Pull request by wxbty**
## What is the purpose of the change
1、Extract the dataComposite common base class
2、Split different types of data （app、service、rt）
3、pkg opt

### CODE REVIEW

**Comment by AlbumenJ** [comment]
Please fix conflicts

**Comment by wxbty** [comment]
> Please fix conflicts
done

**Review by AlbumenJ — APPROVED** [review]
LGTM
@songxiaosheng PTAL

**Review by songxiaosheng — APPROVED** [review]
LGTM

**Pull request merged**
