### PR TITLE
Update StandardMetadataServiceURLBuilder.java

### PR DESCRIPTION
**Pull request by xm101**
修复SIDE_KEY设置被覆盖，导致服务端线程池被覆盖问题
issues:https://github.com/apache/dubbo/issues/12683

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [x] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
Already fixed in #11936

**Comment by xm101** [comment]
> Already fixed in #11936

应该不是同个问题，11936是本服务的MetadataService线程池覆盖了业务接口线程池，而这个issues的问题是，业务接口线程池被调用的其他服务暴露出来的MetadataService生成的客户端线程池所覆盖

**Comment by AlbumenJ** [comment]
> > Already fixed in #11936
> 
> 应该不是同个问题，11936是本服务的MetadataService线程池覆盖了业务接口线程池，而这个issues的问题是，业务接口线程池被调用的其他服务暴露出来的MetadataService生成的客户端线程池所覆盖

#11936 这个修复直接把 MetadataService 配置的线程池给删除了

**Comment by xm101** [comment]
> 

如果我没看错的话，https://github.com/apache/dubbo/pull/11936 修复的是暴露本服务MetadataService时的线程池，修改的是ConfigurableMetadataServiceExporter.java，而我发现的是refer，引用其他服务的MetadataService，一个是服务端线程池，一个是客户端线程池，及时这边删除了线程池配置也不合理，这里是为了调用remote获取其他服务的metadata信息，不应该复用服务端线程池，side也不应该为provider，应该是consumer，而源码中也设置了，只是被注册中心的信息覆盖，详见https://github.com/apache/dubbo/issues/12683 的代码截图

**Comment by xm101** [comment]
> 如果我没看错的话，#11936 修复的是暴露本服务MetadataService时的线程池，修改的是ConfigurableMetadataServiceExporter.java，而我发现的是refer，引用其他服务的MetadataService，一个是服务端线程池，一个是客户端线程池，及时这边删除了线程池配置也不合理，这里是为了调用remote获取其他服务的metadata信息，不应该复用服务端线程池，side也不应该为provider，应该是consumer，而源码中也设置了，只是被注册中心的信息覆盖，详见#12683 的代码截图

**Review by AlbumenJ — APPROVED** [review]

**Pull request merged**
