### PR TITLE
feat:Remove zk3.4 support in 3.3

### PR DESCRIPTION
**Pull request by RainYuY**
## What is the purpose of the change

refer:[#13960](https://github.com/apache/dubbo/issues/13960)

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by RainYuY** [comment]
Refer: CI [#19](https://github.com/apache/dubbo-integration-cases/pull/19)

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
@CrazyHZM @chickenlj PTAL

**Comment by AlbumenJ** [comment]
Please check why test cases failed

**Comment by RainYuY** [comment]
> Please check why test cases failed

The new error is:` Could not find artifact org.apache.dubbo:dubbo-dependencies-zookeeper-curator5:pom:3.3.0-beta.2-SNAPSHOT`
I think I should modify the Maven dependencies for these test cases from `curator5` to `zookeeper` after this PR has been merged.

**Comment by AlbumenJ** [comment]
> > Please check why test cases failed
> 
> The new error is:` Could not find artifact org.apache.dubbo:dubbo-dependencies-zookeeper-curator5:pom:3.3.0-beta.2-SNAPSHOT` I think I should modify the Maven dependencies for these test cases from `curator5` to `zookeeper` after this PR has been merged.

Pls update the test cases first

**Comment by RainYuY** [comment]
After thinking and discussing, maybe removing the old ZooKeeper but not renaming `zookeeper-curator5` is a better choice to avoid new CI failures.

**Comment by RainYuY** [comment]
new PR:refer: [#14028](https://github.com/apache/dubbo/pull/14028)

**Pull request closed without merging**
