### PR TITLE
fix: Resolved issue where ServiceInfo with null protocol was blocking…

### PR DESCRIPTION
**Pull request by QingJuBaiTang**
… the refresh of invokers

## What is the purpose of the change
If a spring cloud service's mapping is uploaded to the metadata center, the protocol field of ServiceInfo obtained through getMatchedServiceInfos is null, which eventually causes the invoker update to fail.

lQLPJwt0DxKVgUvNA1TNCeSwWN68PTPd3i0GeOGKdzg7AA_2532_852

## Checklist
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by wcy666103** [comment]
please re-submit in english only.

**Comment by wcy666103** [comment]
use `mvn  spotless:apply` to format code

**Comment by AlbumenJ** [comment]
We should remove `SpringCloudServiceInstanceNotificationCustomizer` in the future

**Comment by QingJuBaiTang** [comment]
Because we are currently using this code and have encountered this bug. Could you please review my fix to see if it actually resolves the issue and does not introduce any other potential problems? @AlbumenJ

**Review by AlbumenJ — APPROVED** [review]

**Pull request merged**
