### PR TITLE
[Dubbo-6000] Fix ReferenceBean cannot be autowired in some situation.

### PR DESCRIPTION
**Pull request by anLA7856**
I write a class named `ReferenceBeanFactoryPostProcessor.class` to solve this problem #6000.
It  go through all beans in SpringContext will store them.
when `postProcessMergedBeanDefinition` in `MergedBeanDefinitionPostProcessor` calls, it will find some beans to call `getBean`.

## What is the purpose of the change

fix `ReferenceBean` cannot be autowired in some situation.

## Brief changelog

1. fix `ReferenceBean` cannot be autowired in some situation.

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by anLA7856** [comment]
Am I need add a license head ? 
Build failed with the message :
```
[ERROR] Failed to execute goal org.apache.rat:apache-rat-plugin:0.12:check (verify.rat) on project dubbo-config-spring: Too many files with unapproved license: 2 See RAT report in: /home/travis/build/apache/dubbo/dubbo-config/dubbo-config-spring/target/rat.txt -> [Help 1]
```

**Comment by tangcent** [comment]
See [CONTRIBUTING](https://github.com/apache/dubbo/blob/master/CONTRIBUTING.md#code-conventions) for details.

- Add the ASF license header comment to all new .java files (copy from existing files in the project)

**Comment by anLA7856** [comment]
Hi, how about of this optimization ?  @mercyblitz

**Comment by AlbumenJ** [comment]
@anLA7856 hi, thanks for your contribution.

Please add the ASF license header comment to all new .java files and resolve confilcts with the latest master branch.

**Comment by anLA7856** [comment]
Hi, @AlbumenJ , I have added ASF license header comment, can the pull request merge into master?
It passed the Unit Test,but failed in Integration Test, I clone the dubbo-samples project and found `org.apache.dubbo.samples.basic.DemoServiceIT` can pass unless there is `org.apache.dubbo.samples.basic.api.DemoService` service, 
that will be provided when  `org.apache.dubbo.samples.basic.BasicProvider` run.

**Comment by kylixs** [comment]
@DubboReference/@Reference is a combination of reference bean + inject, but the reference bean is not registered in the spring bean factory, so it will not be found if you use @autowire injection elsewhere. 
The following configuration is confusing: 
Whether to inject a reference bean or register a reference bean for other classes to use? It also conflicts with the original design of @DubboReference, when it appears in a non java configuration class, it will be strange to register it in the spring container.
```
@Configuration
public class XXX {
    @Reference(version = "1.0.0", check = false)
    HelloService helloService;
}
```
@DubboReference has some problems in the design, I think it is best to define a new Annotation to achieve this behavior.

**Comment by kylixs** [comment]
This problem has been fixed in [Refactor dubbo reference processing #7383]( https://github.com/apache/dubbo/pull/7383)

**Pull request closed without merging**
