### PR TITLE
improve InvokerInvocationHandler#invoke

### PR DESCRIPTION
**Pull request by hengyunabc**

### CODE REVIEW

**Comment by htynkn** [comment]
This change is quite clean to me. but I'm a litte concern about code readability.

Original code is check method name first and then check params, it's straightforward to understand.
Refactored code will check params first and then check method name.

I would like to wait sometime to see other opinion.

**Comment by lkj41110** [comment]
> This change is quite clean to me. but I'm a litte concern about code readability.
> 
> Original code is check method name first and then check params, it's straightforward to understand.
> Refactored code will check params first and then check method name.
> 
> I would like to wait sometime to see other opinion.

`Original code is check method name first and then check params`，我也比较同意这个。
用`&&`时，当前面的表达式不成立的时候不会对参数个数进行判断了，而这个修改先判断参数个数，理论上增加了判断的次数

**Comment by hengyunabc** [comment]
先判断 length，是因为这个最高效，远比判断多次String equals要快。

**Comment by chickenlj** [comment]
I think we can sacrifice readability for performant in this case.

**Pull request merged**
