### PR TITLE
AMS realize dubbo Proxy

### PR DESCRIPTION
**Pull request by githublaohu**
## What is the purpose of the change
 For high performance（为了高的性能）

## Brief changelog
See the unit tests in the test directory（请看test 目录下的单元测试）

## Verifying this change
See the unit tests in the test directory（请看test 目录下的单元测试）

A couple of questions
1. When the formal parameters of the method exceed 6, it will be abnormal.
2. Exception setting. There are multiple exception points in asm implementation.

有几个问题
1. 当方法的形参超过6个就会异常，怎么比对都没有发现问题在哪里。
2. 异常设定，asm实现里面有多个异常点，请问这些异常有异常类的提供吗？

### CODE REVIEW

**Comment by chickenlj** [comment]
I remember the proxy mechanism of Dubbo is extensible with some well-designed SPIs. Currently, we have JDK, Javassist supported. ASM is definitely another good choice, could you please check if we can support ASM by making it another option as the other two?

**Comment by hengyunabc** [comment]
个人意见：

* 直接使用asm会让代码非常难看懂，有问题的话，也比较难查。一不小心的话，栈不配平，或者参数没匹配上就会出错。如果有异常处理的话，更是复杂和难理解。

* ClassLoader/ClassPath 会有很多的dark corner，已经在Javassist本身里处理掉的。直接用asm可能会遇到

**Comment by githublaohu** [comment]
是的，asm兼容性问题值得重点关注，谢谢。
我已经做了大量的单元测试。尽量覆盖所有场景。




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            2372554140
                            
                            
                                
                                    邮箱：2372554140@qq.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 12/13/2019 10:54, hengyunabc wrote: 个人意见：


直接使用asm会让代码非常难看懂，有问题的话，也比较难查。一不小心的话，栈不配平，或者参数没匹配上就会出错。如果有异常处理的话，更是复杂和难理解。


ClassLoader/ClassPath 会有很多的dark corner，已经在Javassist本身里处理掉的。直接用asm可能会遇到



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/dubbo/pull/5146?email_source=notifications\u0026email_token=ACCGO6V5VJTWJVVEGK3D7D3QYL2PJA5CNFSM4I6P7NL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGYXSII#issuecomment-565279009",
"url": "https://github.com/apache/dubbo/pull/5146?email_source=notifications\u0026email_token=ACCGO6V5VJTWJVVEGK3D7D3QYL2PJA5CNFSM4I6P7NL2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEGYXSII#issuecomment-565279009",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AlbumenJ** [comment]
@githublaohu Thanks for your contribution.
As for the complexity and incomplete controllability of ASM, it will cause make Dubbo unstable which is quite important in production environment. I am afriad that we cannot accept this PR for current. Please feel free to reopen if you have any question or we can discuss in mailing list (dev@dubbo.apache.org).

**Pull request closed without merging**
