### PR TITLE
Fix wrong return types for StubMethodDescriptor

### PR DESCRIPTION
**Pull request by namelessssssssssss**
**The `StubMethodDescriptor` seems to have wrong `returnTypes` when initialized.**
```Java
   public StubMethodDescriptor(String methodName,
        Class<?> requestClass,
        Class<?> responseClass,
        StubServiceDescriptor serviceDescriptor,
        RpcType rpcType,
        Pack requestPack,
        Pack responsePack,
        UnPack requestUnpack,
        UnPack responseUnpack) {
        this.methodName = methodName;
        this.serviceDescriptor = serviceDescriptor;
        this.rpcType = rpcType;
        this.requestPack = requestPack;
        this.responsePack = responsePack;
        this.responseUnpack = responseUnpack;
        this.requestUnpack = requestUnpack;
        this.parameterClasses = new Class<?>[]{requestClass};
        this.returnClass = responseClass;
        this.paramDesc = ReflectUtils.getDesc(parameterClasses);
        this.compatibleParamSignatures = Stream.of(parameterClasses).map(Class::getName).toArray(String[]::new);
       //It this correct?
        this.returnTypes = new Type[]{requestClass, requestClass};
        serviceDescriptor.addMethod(this);
    }

```
This problem has no effect if we only use triple protocol, because `TripleInvoker` only use param `returnClass` to get method return type. 
But it may cause a serialization problem when other protocols use protobuf serialization with triple stub.

### CODE REVIEW

**Review by AlbumenJ — APPROVED** [review]
@EarthChen @icodening PTAL

**Comment by namelessssssssssss** [comment]
issue https://github.com/apache/dubbo/issues/13158

**Review by EarthChen — APPROVED** [review]
LGTM

**Comment by AlbumenJ** [comment]
Please also fix on 3.2

**Pull request merged**
