### PR TITLE
Add create dynamic port when user config the port 0.

### PR DESCRIPTION
**Pull request by xieyucan**
## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by plusmancn** [comment]
@xieyucan Where is the target issue? Please write here.

**Comment by xieyucan** [comment]
Thanks, There is no target issue,  just adding new function。发自我的iPhone------------------ Original ------------------From: plusmancn  ***@***.***>Date: Thu,Sep 9,2021 3:41 PMTo: apache/dubbo ***@***.***>Cc: Bruce Xie ***@***.***>, Mention ***@***.***>Subject: Re: [apache/dubbo] Add create dynamic port when user config the port0. (#8732)
@xieyucan Where is the target issue? Please write here.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/apache/dubbo/pull/8732#issuecomment-915843141",
"url": "https://github.com/apache/dubbo/pull/8732#issuecomment-915843141",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by AlbumenJ** [comment]
Could you please describe why you adding these functions?

**Comment by xieyucan** [comment]
> Could you please describe why you adding these functions?

Like tomcat, create dynamic port when user config the port 0。

**Comment by xieyucan** [comment]
> Could you please describe why you adding these functions?

Create dynamic port when user config server port 0.

**Pull request closed without merging**
