### PR TITLE
[Dubbo-4882] Add support for overriding Map properties in AbstractConfig.refresh

### PR DESCRIPTION
**Pull request by mzorro**
Solution for issue #4882 
Add support for overriding Map properties in AbstractConfig.refresh, for example if we have configuration `dubbo.application.parameters=a=1&b=2`, then `ApplicationConfig.refresh` will do `parameters.put("a", "1");parameters.put("b", "2")`.

**The format has been changed to `dubbo.application.parameters=[{a:1}, {b:2}}]`**

### CODE REVIEW

**Comment by beiwei30** [comment]
@mzorro would you mind take a look at https://github.com/mzorro/dubbo/pull/1? My idea is we should try to limit changes in AbstractConfig by splitting the logics into smaller methods, instead of moving them into other places. 

The reason is the current implementation in AbstractConfig is not good enough. It should help us to make it better if we put all relevant code in one single class.

**Comment by mzorro** [comment]
> @mzorro pls. check my comment.

thanks for the help, I have merged your PR

**Comment by chickenlj** [comment]
change format to `dubbo.application.parameters=[{a:1}, {b:2}]`

**Comment by mzorro** [comment]
> change format to `dubbo.application.parameters=[{a:1}, {b:2}]`

@chickenlj why do you think this format is more readable? It's not even standard JSON.

**Pull request merged**
