### PR TITLE
[3.0] Enhance ExtensionLoaderTest

### PR DESCRIPTION
**Pull request by wangchengming666**
1. enhance ExtensionLoaderTest
2. remove unused code and clean code

### CODE REVIEW

**Review by BurningCN — APPROVED** [review]
LGTM

**Comment by AlbumenJ** [comment]
Please resolve conflict

**Comment by wangchengming666** [comment]
> Please resolve conflict

done, thanks

**Review by xiaoheng1 — APPROVED** [review]
LGTM

**Pull request merged**
