### PR TITLE
Add Github Action for Unit test

### PR DESCRIPTION
**Pull request by AlbumenJ**
## What is the purpose of the change

Add Github Action Support for Dubbo Unit Test

### CODE REVIEW

**Comment by htynkn** [comment]
Changes looks good to me.

but there are few things need to be discuss before merge it:
+ are we going to disable travis-ci (it doesn't make sense to have both them, it will waste resource and time)
+ what platform do we use? I prefer linux-jdk8 and linux-jdk11. maybe windows too. but for macos, the lack of action runner will lead a long time to wait
+ different concurrency limit between github action and travis ci (refer to https://www.mail-archive.com/builds@apache.org/msg07478.html)

**Comment by AlbumenJ** [comment]
hi, @htynkn 

> what platform do we use? I prefer linux-jdk8 and linux-jdk11. maybe windows too. but for macos, the lack of action runner will lead a long time to wait

yeap, I agree with you. I will disable macOS test case later on.

> different concurrency limit between github action and travis ci (refer to https://www.mail-archive.com/builds@apache.org/msg07478.html)

According to [Github Community](https://github.community/t/actions-usage-for-a-public-repo-on-a-large-org/16880/2), we can use at least up to 20 workflows concurrently for dubbo repo itself. For now it is enough for our building rate on [travis](https://travis-ci.org/github/apache/dubbo/builds).

**Comment by AlbumenJ** [comment]
`DirtiesContext` has been added to all of the test classes in `dubbo-config-spring` module. In different platform, the exection order of test cases is different and this may causes environment pollution. `DirtiesContext` can fix it.

**Review by htynkn — APPROVED** [review]
thanks for your investigate and contribution.

Will merge this change to master soon.
At this stage, I can see some duplicate code in github action yml file, maybe we can use some  feature like `matrix` to make it more clean. those stuff can be done in the future.

**Pull request merged**
