### PR TITLE
[Dubbo-4331] Improve api doc #4331

### LINKED ISSUE #4331: [API-DOC] Improve api doc
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

API DOC is generated with `./mvnw clean javadoc:aggregate -Dmaven.javadoc.skip=false`
But there are something need improve for those docs.

+ demo should exclude from docs
+ doc title is using dubbo-parent, should be Apache Dubbo

### PR DESCRIPTION
**Pull request by sonymoon**
## What is the purpose of the change
fix #4331 

 
Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by sonymoon** [comment]
This should work: `./mvnw clean javadoc:aggregate -Dmaven.javadoc.skip=false -Prelease` in my local OS. Just need a profile specified and some plugin configurations.

**Comment by sonymoon** [comment]
```
INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:18 min
[INFO] Finished at: 2019-09-16T11:36:35Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.0:testCompile (default-testCompile) on project dubbo-rpc-dubbo: Compilation failure
[ERROR] error: error reading /home/travis/.m2/repository/org/glassfish/javax.el/3.0.1-b08/javax.el-3.0.1-b08.jar; error in opening zip file
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :dubbo-rpc-dubbo
/home/travis/.travis/functions: line 537:  4348 Terminated              travis_jigger "${!}" "${timeout}" "${cmd[@]}"
travis_time:end:06a84ff2:start=1568633355964402712,finish=1568633795937931705,duration=439973528993,event=script
[0K[31;1mThe command "travis_wait 30 ./mvnw --batch-mode --no-transfer-progress clean install -DskipTests=false -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true" exited with 1.[0m
```

CI Failed. Not related to this PR.

**Comment by sonymoon** [comment]
Could someone re-trigger CI test ? ping @chickenlj @cvictory

**Comment by sonymoon** [comment]
I would be very appreciated if you help review @htynkn.

**Comment by htynkn** [comment]
What maven command should use with this change?
I try `./mvnw clean javadoc:aggregate -Dmaven.javadoc.skip=false` somehow those changes can't apply to javadoc

**Comment by sonymoon** [comment]
> What maven command should use with this change?
> I try `./mvnw clean javadoc:aggregate -Dmaven.javadoc.skip=false` somehow those changes can't apply to javadoc

`./mvnw clean javadoc:aggregate -Dmaven.javadoc.skip=false -Prelease` . 
`-P release` is required because the javadoc maven plugin  is configured  under profile `release` 
@htynkn

**Pull request merged**
