### PR TITLE
fix no such extension by name netty4

### PR DESCRIPTION
**Pull request by icodening**
## What is the purpose of the change
fix no such extension by name netty4

image

### CODE REVIEW

**Review by AlbumenJ — COMMENTED** [review]
I wonder if user configure `netty 3` in properties what will happen?

**Review by AlbumenJ — APPROVED** [review]
Others look good to me

**Comment by icodening** [comment]
> I wonder if user configure `netty 3` in properties what will happen?

`No such extension org.apache.dubbo.remoting.api.pu.PortUnificationTransporter by name netty3`
current version does not support `netty3`.  change `netty4` to be compatible with lower version

**Comment by AlbumenJ** [comment]
> > I wonder if user configure `netty 3` in properties what will happen?
> 
> `No such extension org.apache.dubbo.remoting.api.pu.PortUnificationTransporter by name netty3` current version does not support `netty3`. change `netty4` to be compatible with lower version

I have create a issue (#10812) for this. We can continue track in that issue.

**Pull request merged**
