### PR TITLE
Update AbstractRegistryFactory.java

### PR DESCRIPTION
**Pull request by yande2011**
[bugfix] 创建registry错误时输出错误日志

## Verifying this change

- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by xiaoheng1 — COMMENTED** [review]
What scene will be abnormal?

**Review by horizonzy — COMMENTED** [review]
It just add log info than before, it's not necessary.

**Comment by yande2011** [comment]
> What scene will be abnormal?

when i config a registry but havent add a dependency or cofig for a not exist registry, the exception does not have a log, every thing seem ok from log,but it does not work property actually

**Comment by yande2011** [comment]
> It just add log info than before, it's not necessary.
编码约定
抛出异常的地方不用打印日志，由最终处理异常者决定打印日志的级别，吃掉异常必需打印日志

**Comment by horizonzy** [comment]
> when i config a registry but havent add a dependency or cofig for a not exist registry, the exception does not have a log, every thing seem ok from log,but it does not work property actually

Yes, the log didn't log this situation. It should be enhanced.
But the code can't fix it. The registryFactory is adaptive, the catch code block can't cover it.

**Comment by yande2011** [comment]
> > when i config a registry but havent add a dependency or cofig for a not exist registry, the exception does not have a log, every thing seem ok from log,but it does not work property actually
> 
> Yes, the log didn't log this situation. It should be enhanced.
> But the code can't fix it. The registryFactory is adaptive, the catch code block can't cover it.

Template Method Pattern is used in the registryFactory, i think it is the proper place to log error message.if other classes implement RegistryFactory and override the adaptive method shold log the message itself.

**Comment by horizonzy** [comment]
> Template Method Pattern is used in the registryFactory, i think it is the proper place to log error message.if other classes implement RegistryFactory and override the adaptive method shold log the message itself.

Hi, If you config zookeeper registry without  zookeeper-registry dependency, it will throw exception before AbstractRegistryFactory.getRegistry(URL url). You can debug the code at your local machine.

**Pull request closed without merging**
