### PR TITLE
Fix hessian2 deserialize bug

### PR DESCRIPTION
**Pull request by mytang0**
## What is the purpose of the change
Fix hessian2 deserialize bug, #11442 

## Verifying this change
#11442

### CODE REVIEW

**Comment by mytang0** [comment]
> Please merge the latest 3.1 branch to your branch

ok, merged.

**Comment by AlbumenJ** [comment]
image

**Comment by mytang0** [comment]
> image

Test code: 
`@SuppressWarnings("unchecked")
    public static void listTest() throws Exception {
        Hessian2Serialization hessian2Serialization = new Hessian2Serialization();

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        ObjectOutput objectOutput = hessian2Serialization.serialize(null, baos);

        // List test
        List<Float> floatList = new ArrayList<>();
        floatList.add(3.5F);
        floatList.add(3.51F);

        objectOutput.writeObject(floatList);
        objectOutput.flushBuffer();
        List<Float> list =
            (List<Float>) hessian2Serialization.deserialize(null, new ByteArrayInputStream(baos.toByteArray()))
                .readObject(List.class, new TypeReference<List<Float>>() {
                }.getType());
    }

    @SuppressWarnings("unchecked")
    public static void mapTest() throws Exception {
        Hessian2Serialization hessian2Serialization = new Hessian2Serialization();

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        ObjectOutput objectOutput = hessian2Serialization.serialize(null, baos);

        // Map test
        HashMap<String, Float> floatMap = new HashMap<>();
        floatMap.put("a", 3.50F);
        floatMap.put("b", 3.54F);

        objectOutput.writeObject(floatMap);
        objectOutput.flushBuffer();
        Map<String, Float> map =
            hessian2Serialization.deserialize(null, new ByteArrayInputStream(baos.toByteArray()))
                .readObject(Map.class, new TypeReference<Map<String, Float>>() {
                }.getType());
    }`


I tested the deserialization of Map locally and it was ok.  
Dubbo 3.1 branch, in hessian-lite version 3.2.13 the map deserializer should be MapDeserializer. Not sure which version of AbstractMapDeserializer is in the error stack?

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
Please merge the latest `3.1` branch into your branch

**Comment by mytang0** [comment]
The original problem of hessian2 makes it difficult to fix bug only through dubbo.

**Pull request closed without merging**
