### PR TITLE
[CI] Add enforce maven plugin to do snapshot version check

### PR DESCRIPTION
**Pull request by htynkn**
## What is the purpose of the change

Creating [a jenkins job](https://builds.apache.org/job/Apache%20Dubbo/job/apache-dubbo-snapshot-deployment/) for deploying snapshot version to apache maven repo.

In order to make everything works well, we need prevent release deploy for this job, so try to add a enforce plugin rule to check all version is snapshot version.

## Brief changelog

modify pom.xml and add new enforce plugin

## Verifying this change

CI pass with
```
./mvnw clean validate -Psnapshot-ci-deploy
```

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/incubator-dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [x] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by ralf0131** [comment]
What command does jenkins job run?

**Comment by htynkn** [comment]
Jenkins will run 
```
./mvnw clean validate -Psnapshot-ci-deploy
```
 to check all version are snapshot.

And for deployment, it will run 
```
./mvnw clean package deploy -f dubbo-dependencies-bom && ./mvnw clean package deploy -DskipTests=true
```
And for commit status check will use a groovy script to do
``` groovy
import groovy.json.JsonSlurper
import java.io.File

def env = System.getenv()
def commitId = env["GIT_COMMIT"]

println "Current commit id: $commitId"

String commitStatusJson = new URL("https://api.github.com/repos/apache/dubbo/commits/$commitId/status").text
println "Commit status: \r\n$commitStatusJson"

def jsonSlurper = new JsonSlurper()
def jsonObject = jsonSlurper.parseText(commitStatusJson)

def status = jsonObject.state

println "Current commit status is $status"

if (status == "sucesss") {
    def newFile = new File("CONTINUE_DEPLOY_FLAG")
    newFile.createNewFile() 
    println "Continue to deploy snapshot"
} else {
    println "Current commit status not allow to deploy snapshot"
}
```

**Comment by ralf0131** [comment]
So the Jenkins job workflow is:
1. check every 30 min
2. check if the latest commit is built successfully (e.g. CI pass)
3. check if it is a snapshot version
4. deploy the snapshot 

Is my understanding correct?

**Comment by htynkn** [comment]
> So the Jenkins job workflow is:
> 
> 1. check every 30 min
> 2. check if the latest commit is built successfully (e.g. CI pass)
> 3. check if it is a snapshot version
> 4. deploy the snapshot
> 
> Is my understanding correct?

Yeah. but for the first one, it will check every 6 hours.
For third one, I will add command after this PR merged

Please refer to latest successfully build: https://builds.apache.org/job/Apache%20Dubbo/job/apache-dubbo-snapshot-deployment/16/

The next step I will try to convert this jenkins job config to a Jenkinsfile(https://jenkins.io/doc/book/pipeline/jenkinsfile/), it will make things more clear and easy to maintain. With Jenkinsfile everyone can see Jenkins job config and send a PR to modify it without Apache account and group access

**Pull request merged**
