### PR TITLE
[master] fix ignored interface name matches method

### LINKED ISSUE #8581: [2.7.13] org.apache.dubbo.common.utils.NetUtils的ignoreNetworkInterface方法处理不了网卡名包含圆括号的环境
### Environment

* Dubbo version: 2.7.13

### Steps to reproduce this issue
NetUtils.ignoreNetworkInterface方法使用matches判断是否是要忽略的网卡，
当网卡名称包含圆括号时，如INTEL(R) XXX
即使完全相同，结果也是false： ”INTEL(R) XXX".matches("INTEL(R) XXX" 结果为false！

比较了3.0的代码，该方法已经删除了DUBBO_NETWORK_IGNORED_INTERFACE相关的处理，建议2.7系列做一下同步修订。

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change
fix #8581

### CODE REVIEW

**Comment by wangchengming666** [comment]
LGTM.

**Review by wangchengming666 — APPROVED** [review]
LGTM.

**Comment by zrlw** [comment]
@wangchengming666  pls review again

**Comment by AlbumenJ** [comment]
Please check if it is necessary to patch to 3.0 branch.

**Comment by zrlw** [comment]
> Please check if it is necessary to patch to 3.0 branch.

#8723

**Pull request merged**
