### PR TITLE
optimize : fix generic specification tips

### PR DESCRIPTION
**Pull request by lzf971107**
## What is the purpose of the change

Fix generic non-standard tips in idea

## Brief changelog

1.dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistry.java
2.dubbo-serialization/dubbo-serialization-api/src/main/java/org/apache/dubbo/common/serialize/support/SerializationOptimizer.java
3.dubbo-serialization/dubbo-serialization-test/src/test/java/org/apache/dubbo/common/serialize/support/SerializableClassRegistryTest.java

## Verifying this change

Passed unit tests

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by htynkn** [comment]
could you fill all information in PR template ？

**Comment by lzf971107** [comment]
> could you fill all information in PR template ？

Oh sorry, of course

**Comment by lzf971107** [comment]
@htynkn 
I'm a bit unfamiliar with the apache specification, thank you for your reminder.

**Comment by htynkn** [comment]
refer to javadoc 8 & 11:

https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html

> Use Class<?> if the class being modeled is unknown.

In this case, what we are dealing is unknown class, so it's no much different between `An unknown class (raw type)` and `An unknown class (generic version)`. so this PR looks ok to me if it can bring extra benefit.

But I have a question,  what do you mean by `generic non-standard tips in idea`, are you talking about Intellij IDEA?

**Comment by lzf971107** [comment]
> refer to javadoc 8 & 11:
> 
> https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html
> https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Class.html
> 
> > Use Class<?> if the class being modeled is unknown.
> 
> In this case, what we are dealing is unknown class, so it's no much different between `An unknown class (raw type)` and `An unknown class (generic version)`. so this PR looks ok to me if it can bring extra benefit.
> 
> But I have a question, what do you mean by `generic non-standard tips in idea`, are you talking about Intellij IDEA?

@htynkn 
Of course, this idea is taken from idea, because idea is a relatively good ide editor in the industry, he has countless experiences to know various specifications, and I think that even if we deal with unknown classes, we have to explicitly declare generics The specification, the type of the declaration, so as to clearly tell the reader, we are dealing with an unknown class, without causing people to wonder.

**Comment by lzf971107** [comment]
@htynkn 
> Use Class<?> if the class being modeled is unknown.
Like this sentence you pointed out, it is also clearly stated in the java doc of Class.java

**Pull request merged**
