### PR TITLE
Speed up registry destroy.

### PR DESCRIPTION
**Pull request by aftersss**
When we shutdown our program, we found that it costs too much time at destroying registry from zookeeper. Consider that if we have 200 urls registered to zookeeper, and every unregister will cost 100ms, it will cost 200*100 = 20000ms to shutdown the program.

This PR uses a thread pool to reduce the shutdown time.

### CODE REVIEW

**Comment by beiwei30** [comment]
> When we shutdown our program, we found that it costs too much time at destroying registry from zookeeper. Consider that if we have 200 urls registered to zookeeper, and every unregister will cost 100ms, it will cost 200*100 = 20000ms to shutdown the program.
> 
> This PR uses a thread pool to reduce the shutdown time.

@aftersss, with your solution, how much time can it save from the shutdown process?

**Comment by aftersss** [comment]
We have `153` providers In one of our applications, when we shutdown this application, `AbstractRegistry.destroy` costs `5394ms`  (I have tested it several times, this is the average time).

If we change `AbstractRegistry.destroy` to let unregister happens concurrently,  `AbstractRegistry.destroy` costs only `213ms`.

**Comment by chickenlj** [comment]
How about the batch operation of zookeeper, have you ever tried?

**Comment by chickenlj** [comment]
Please solve the conflicts and reopen.

More importantly, I am not sure if there are any side effects if we make the unregister process parallel and async.

**Comment by chickenlj** [comment]
I tend to keep it as it is now and wait for more feedback.

**Pull request closed without merging**
