### PR TITLE
chore: Use ReentrantLock for loading Extension Classes

### PR DESCRIPTION
**Pull request by He-Pin**
## What is the purpose of the change
It blocked the carrier, I wanted to do it in no blocking way, but that will require more changes.

```java
Thread[#537,ForkJoinPool-1-worker-1,5,CarrierThreads]
    java.base/java.lang.VirtualThread$VThreadContinuation.onPinned(VirtualThread.java:183)
    java.base/jdk.internal.vm.Continuation.onPinned0(Continuation.java:393)
    java.base/java.lang.VirtualThread.park(VirtualThread.java:582)
    java.base/java.lang.System$2.parkVirtualThread(System.java:2643)
    java.base/jdk.internal.misc.VirtualThreads.park(VirtualThreads.java:54)
    java.base/java.util.concurrent.locks.LockSupport.park(LockSupport.java:219)
    java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:754)
    java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1099)
    java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:230)
    org.apache.dubbo.common.utils.ClassLoaderResourceLoader.loadResources(ClassLoaderResourceLoader.java:58)
    org.apache.dubbo.common.extension.ExtensionLoader.loadDirectoryInternal(ExtensionLoader.java:1051)
    org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:974)
    org.apache.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:962)
    org.apache.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:939) <== monitors:1
    org.apache.dubbo.common.extension.ExtensionLoader.getSupportedExtensions(ExtensionLoader.java:601)
    org.apache.dubbo.common.extension.ExtensionLoader.getSupportedExtensionInstances(ExtensionLoader.java:608)
    com.taobao.hsf.threadpool.ThreadCleanUpUtil.<clinit>(ThreadCleanUpUtil.java:15)
    com.taobao.hsf.message.HSFServerHandler.beforeThreadExecuteCleanUp(HSFServerHandler.java:279)
    com.taobao.hsf.message.HSFServerHandler.access$000(HSFServerHandler.java:42)
    com.taobao.hsf.message.HSFServerHandler$RequestHandler.run(HSFServerHandler.java:122)
    com.taobao.wireless.amp.log.util.LogAwareEagleAsyncRunnable.run(LogAwareEagleAsyncRunnable.java:33)
    java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
    java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
    java.base/java.lang.VirtualThread.run(VirtualThread.java:309)
```

## Brief changelog
Make use of `ReentrantLock` to load extension classes.

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [x] GitHub Actions works fine on your own branch.
- [x] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by AlbumenJ** [comment]
Seems that JDK 23 EA has resolve the pining.

https://mail.openjdk.org/pipermail/loom-dev/2024-February/006433.html

**Comment by He-Pin** [comment]
Cool, thanks for the update,  can't wait the next LTS.

**Comment by He-Pin** [comment]
@AlbumenJ At $Work we can't use non-LTS version Java, so I would like to see this get merged.

**Comment by He-Pin** [comment]
@AlbumenJ Thanks.

**Pull request merged**
