### PR TITLE
refactor condition router

### PR DESCRIPTION
**Pull request by wanghbxxxx**
## What is the purpose of the change
to reduce Cognitive complexity

## Brief changelog

refactor inner class MatchPair: use jdk1.8 stream 
refactor matchCondition method: extract method: getConditionValue

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by wanghbxxxx** [comment]
> Whether to consider refactoring by module

对不起，我英文不太好，不明白这句话是什么意思？

**Comment by CrazyHZM** [comment]
> > Whether to consider refactoring by module
> 
> 对不起，我英文不太好，不明白这句话是什么意思？

我的意思是是否可以按照模块的来进行重构或者优化

**Comment by wanghbxxxx** [comment]
> 
> 我的意思是是否可以按照模块的来进行重构或者优化

我刚刚开始尝试提交代码，看到哪需要就重构一下，谢谢你的建议

**Comment by AlbumenJ** [comment]
@wanghbxxxx hi, thanks for your contribution.

pls resolve conflicts with the latest master branch

@wanghbxxxx 感谢你所做出的贡献，麻烦请合并最新 master 分析到开发分支已解决冲突问题

**Comment by AlbumenJ** [comment]
close for long time no response

Please feel free to reopen if you have any question.

If you think these changes are still useful in the latest branch, please submit a new pull reqeust.

**Pull request closed without merging**
