### PR TITLE
[Dubbo-6746]fix generic interface metadata publish log error

### PR DESCRIPTION
**Pull request by owen200008**
## What is the purpose of the change

fix generic interface metadata publish log error

## Brief changelog

fix generic interface metadata publish log error

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by AlbumenJ** [comment]
@owen200008  hi, could you please describe why you create this pr? Would this fix any issues?

**Comment by owen200008** [comment]
when use generic and the interface not in the jar the log will be error.

we have project to proxy remote real dubbo service, the peoject use generic interface to proxy, so we find many error log

**Comment by owen200008** [comment]
确实写了比较久了，使用泛型代理远程dubbo服务的时候一个接口会报一次error，就是这个去掉error日志
实际我们是知道interface的

如果有时间其他几个也审核下
#6720 
#6766

**Comment by owen200008** [comment]
#6535
remote exception support fastjson serialization

**Review by chickenlj — APPROVED** [review]
LGTM.

**Pull request merged**
