### PR TITLE
Fix URLBuilder#addParametersIfAbsent (#7761)

### PR DESCRIPTION
**Pull request by icankeep**
## What is the purpose of the change

Fix URLBuilder#addParametersIfAbsent 

see more information from #7761

- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by xiaoheng1 — COMMENTED** [review]
It might be better to use addParameterIfAbsent instead of this.parameters.putIfAbsent(entry.getKey(), entry.getValue());

**Comment by BurningCN** [comment]
> It might be better to use addParameterIfAbsent instead of this.parameters.putIfAbsent(entry.getKey(), entry.getValue());

Calling the `addParameterIfAbsent` method may cause multiple URL creations

**Comment by xiaoheng1** [comment]
> addParameterIfAbsent

Can you describe in detail  why may cause multiple URL creations ？

What I mean is to amend as follows:

for(Map.Entry<String, String> entry: parameters.entrySet()) {
             addParameterIfAbsent(entry.getKey(), entry.getValue());
         }

This operation is all in the same URLBuilder

**Comment by BurningCN** [comment]
> > addParameterIfAbsent
> 
> Can you describe in detail why may cause multiple URL creations ？
> 
> What I mean is to amend as follows:
> 
> for(Map.Entry<String, String> entry: parameters.entrySet()) {
> addParameterIfAbsent(entry.getKey(), entry.getValue());
> }
> 
> This operation is all in the same URLBuilder

Sorry, I read the wrong class. You are talking about the `URLBuilder` class, but I have always looked at the `URL` class.
As you described it is correct.

**Comment by xiaoheng1** [comment]
> Sorry, I read the wrong class. You are talking about the `URLBuilder` class, but I have always looked at the `URL` class.
> As you described it is correct.

ok.

**Comment by icankeep** [comment]
> It might be better to use addParameterIfAbsent instead of this.parameters.putIfAbsent(entry.getKey(), entry.getValue());

good idea

**Review by xiaoheng1 — APPROVED** [review]
LGTM

**Comment by pinxiong** [comment]
> > It might be better to use addParameterIfAbsent instead of this.parameters.putIfAbsent(entry.getKey(), entry.getValue());
> 
> good idea

@icankeep Can this PR be closed? If it's necessary, we can open it again. #7761 too.

**Review by AlbumenJ — APPROVED** [review]

**Comment by xiaoheng1** [comment]
&READY-TO-CLOSE&

**Pull request merged**
