### PR TITLE
[ISSUE #9721] add memory limited linked blocking queue

### PR DESCRIPTION
**Pull request by dragon-zhang**
Can completely solve the OOM problem caused by {@link java.util.concurrent.LinkedBlockingQueue}.

### CODE REVIEW

**Comment by AlbumenJ** [comment]
Are there any usages of `MemoryLimitedLinkedBlockingQueue`?

**Comment by dragon-zhang** [comment]
Oh, maybe I need to add a new Threadpool impl and some testcase ?



发自我的iPhone


------------------ Original ------------------
From: Albumen Kevin ***@***.***&gt;
Date: Sun,Feb 27,2022 7:36 PM
To: apache/dubbo ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/dubbo] [ISSUE #9721] add memory limited linked blocking queue (PR #9722)





 
Are there any usages of MemoryLimitedLinkedBlockingQueue?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dragon-zhang** [comment]
I has add a testcase, you can see it in `org.apache.dubbo.common.threadpool.support.limited.MemoryLimitedLinkedBlockingQueueTest#test`.



发自我的iPhone


------------------ Original ------------------
From: Albumen Kevin ***@***.***&gt;
Date: Sun,Feb 27,2022 7:36 PM
To: apache/dubbo ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/dubbo] [ISSUE #9721] add memory limited linked blocking queue (PR #9722)





 
Are there any usages of MemoryLimitedLinkedBlockingQueue?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by chickenlj** [comment]
What's the meaning or purpose of adding this new Queue implementation, can you please name the Queues that need to be replaced by this one in the current repository?  So we can decide if it's necessary to have this implementation for the time being.

**Comment by dragon-zhang** [comment]
```java
public class FixedThreadPool implements ThreadPool {

    public static final String NAME = "fixed";

    @Override
    public Executor getExecutor(URL url) {
        String name = url.getParameter(THREAD_NAME_KEY, DEFAULT_THREAD_NAME);
        int threads = url.getParameter(THREADS_KEY, DEFAULT_THREADS);
        int queues = url.getParameter(QUEUES_KEY, DEFAULT_QUEUES);
        return new ThreadPoolExecutor(threads, threads, 0, TimeUnit.MILLISECONDS,
                queues == 0 ? new SynchronousQueue<Runnable>() :
                        (queues < 0 ?
                                //here can be replace to MemoryLimitedLinkedBlockingQueue
                                //for example, limit the maximum memory used by this queue to 100MB
                                new LinkedBlockingQueue<Runnable>()
                                : new LinkedBlockingQueue<Runnable>(queues)),
                new NamedInternalThreadFactory(name, true), new AbortPolicyWithReport(name, url));
    }

}
```

**Comment by chickenlj** [comment]
Sorry. Please submit the same PR to the 3.0 branch, we will only accept bug fixes for the master branch.

**Comment by dragon-zhang** [comment]
ok



发自我的iPhone


------------------ Original ------------------
From: ken.lj ***@***.***&gt;
Date: Tue,Mar 15,2022 9:03 PM
To: apache/dubbo ***@***.***&gt;
Cc: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [apache/dubbo] [ISSUE #9721] add memory limited linked blocking queue (PR #9722)





 
Sorry. Please submit the same PR to the 3.0 branch, we will only accept bug fixes for the master branch.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dragon-zhang** [comment]
see https://github.com/apache/dubbo/pull/9789

**Pull request merged**
