### PR TITLE
set lazy init to true of reference bean to prevent early initialization.

### PR DESCRIPTION
**Pull request by mooseen**
solve issue https://github.com/apache/dubbo/pull/5710#issuecomment-626097717

### CODE REVIEW

**Comment by kylixs** [comment]
Setting lazy init true does not prevent early initialization. By default `allowEagerInit` is true, only abstract beanDefinition will be ignored.
Please check `org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType()`

**Comment by kylixs** [comment]
通过设置targetType伪装为一个普通bean从而可以避免提前初始化，但在实际初始化时还是根据beanClass生成原来的FactoryBean，也不影响正常初始化。但这个方法可能不是很可靠，有可能在以后某个Spring版本失效。

**Comment by kylixs** [comment]
* `generic=true` 泛型调用时`interfaceClass`不是用`interfaceName`，而是`GenericService.class`
* 使用`RootBeanDefinition.setDecoratedDefinition()` 可以更优雅实现此pr的功能

**Comment by AlbumenJ** [comment]
@mooseen hi, thanks for your contribution.

Currently, we are reformatting the spring related code and make it more robust. The issue this pr fixes will be fixed in the future.

Please feel free to reopen if you hava any question.

**Comment by kylixs** [comment]
This problem has been fixed in [Refactor dubbo reference processing #7383]( https://github.com/apache/dubbo/pull/7383)

**Pull request closed without merging**
