### PR TITLE
feat: build ConfigCenter url with username and password (#6723)

### PR DESCRIPTION
**Pull request by fishautumn**
## What is the purpose of the change

`ConfigCenterConfig` doesn't honor username and password in `toUrl` method. It requires specifying username/password in `address` filed.

When working with spring-boot and dubbo-registry-nacos, it required bellow config:
```yaml
dubbo:
  application:
    name: demo-client
  registry:
    register: false
    address: nacos://nacos-server?username={username}&password={password}
```

It seems hacky. After this change, it becomes:
```yaml
dubbo:
  registry:
    address: nacos://nacos-server
    username: nacos_test
    password: nacos_test
```

## Brief changelog

simply add username and password when building the URL.

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [X] Each commit in the pull request should have a meaningful subject line and body.
- [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7 **YES, necessary**
- [X] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [X] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by AlbumenJ** [comment]
Please check if `3.1` branch has the same issue. The `master` branch (`2.7.x` version) will no longer merge any bugfix.

**Comment by fishautumn** [comment]
> Please check if `3.1` branch has the same issue. The `master` branch (`2.7.x` version) will no longer merge any bugfix.

Got it.

I tried with dubbo-3.1.1, it authenticated correctly with username/password. So no need to patch Dubbo 3.

**Comment by CrazyHZM** [comment]
The master branch (2.7.x version) will no longer merge any bugfix.

**Comment by CrazyHZM** [comment]
The master branch (2.7.x version) will no longer merge any bugfix. Close this PR now.

**Pull request closed without merging**
