### PR TITLE
Add support for error code metrics (#12125)

### PR DESCRIPTION
**Pull request by namelessssssssssss**
## What is the purpose of the change
Add support for error code metrics.

## Brief changelog
* ​The error code metric is sampled when log is enabled.

### CODE REVIEW

**Comment by namelessssssssssss** [comment]
@wxbty  @songxiaosheng  @AlbumenJ  PTAL  :)

**Review by wxbty — CHANGES_REQUESTED** [review]
Whether to consider using a unified event api, such as EventBus

**Comment by namelessssssssssss** [comment]
> Whether to consider using a unified event api, such as EventBus
dubbo-common doesn't import guava, I think it might be better to use a custom implementation in this simple scene

**Comment by wxbty** [comment]
> > Whether to consider using a unified event api, such as EventBus
> 
> dubbo-common doesn't import guava, I think it might be better to use a custom implementation in this simple scene

MetricsEventBus，The rest of the metrics collection uses this uniformly

**Comment by namelessssssssssss** [comment]
> > > Whether to consider using a unified event api, such as EventBus
> > 
> > 
> > dubbo-common doesn't import guava, I think it might be better to use a custom implementation in this simple scene
> 
> MetricsEventBus，The rest of the metrics collection uses this uniformly

That will import dubbo-metrics-api into dubbo-common.  But later maybe we can split out metrics-event from metrics-api to solve this problem, that can be a part of dubbo-core refactor.

**Comment by AlbumenJ** [comment]
This is a feature, so I have change it to `3.3`

**Review by songxiaosheng — APPROVED** [review]
LGTM

**Comment by AlbumenJ** [comment]
image

Please resolve conflicts

**Pull request merged**
