### PR TITLE
[Dubbo-6519] fix issue:#6519 http protocol genericService.$invokeAsync ClassCastException

### PR DESCRIPTION
**Pull request by iqinning**
## What is the purpose of the change

fix issue:#6519 http protocol genericService.$invokeAsync ClassCastException

## Brief changelog

dubbo-rpc-http/org.apache.dubbo.rpc.protocol.http.filter.HttpAsyncFilter
dubbo-rpc-http/org.apache.dubbo.rpc.protocol.http.HttpProtocolTest.testGenericAsyncInvoke

## Verifying this change

```
@Test
    public void testGenericAsyncInvoke() throws InterruptedException, ExecutionException {
        HttpServiceImpl server = new HttpServiceImpl();
        Assertions.assertFalse(server.isCalled());
        ProxyFactory proxyFactory = ExtensionLoader.getExtensionLoader(ProxyFactory.class).getAdaptiveExtension();
        Protocol protocol = ExtensionLoader.getExtensionLoader(Protocol.class).getAdaptiveExtension();
        int port = NetUtils.getAvailablePort();
        URL url = URL.valueOf("http://127.0.0.1:" + port + "/" + HttpService.class.getName() + "?release=2.7.0");
        Exporter<HttpService> exporter = protocol.export(proxyFactory.getInvoker(server, HttpService.class, url));
        Invoker<GenericService> invoker = protocol.refer(GenericService.class, url);
        GenericService client = proxyFactory.getProxy(invoker, true);
        CompletableFuture future = client.$invokeAsync("sayHello", new String[]{"java.lang.String"}, new Object[]{"haha"});
        Assertions.assertTrue(server.isCalled());
        Assertions.assertEquals("Hello, haha", future.get());
        invoker.destroy();
        exporter.unexport();
    }
```

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by iqinning** [comment]
#6519

**Comment by chickenlj** [comment]
Most probably, other protocols that are integrated with Dubbo like HTTP have the same issue. Considering fixing it in AbstractProxyProtocol would be a more generalized solution.

**Comment by chickenlj** [comment]
I have checked and it's mainly because of the `CompletableFuture` signature. All third-party protocols integrated currently don't support the method of `CompletableFuture` signature.

I highly recommend using `$invoke` method directly instead of adding a new  Filter to do this. Or I don't think it's necessary  to add this HTTP Filter as a general feature.

**Comment by chickenlj** [comment]
```java
protected <T> T doRefer(final Class<T> serviceType, URL url) throws RpcException {
        String generic = url.getParameter("generic");
        boolean isGeneric = ProtocolUtils.isGeneric(generic) || serviceType.equals(GenericService.class);
        JsonProxyFactoryBean jsonProxyFactoryBean = new JsonProxyFactoryBean();
        JsonRpcProxyFactoryBean jsonRpcProxyFactoryBean = new JsonRpcProxyFactoryBean(jsonProxyFactoryBean);
        jsonRpcProxyFactoryBean.setRemoteInvocationFactory((methodInvocation) -> {
            RemoteInvocation invocation = new JsonRemoteInvocation(methodInvocation);
            if (isGeneric) {
                invocation.addAttribute("generic", generic);
            }

            return invocation;
        });
        String key = url.setProtocol("http").toIdentityString();
        if (isGeneric) {
            key = key + "/" + "generic";
        }

        jsonRpcProxyFactoryBean.setServiceUrl(key);
        jsonRpcProxyFactoryBean.setServiceInterface(serviceType);
        jsonProxyFactoryBean.afterPropertiesSet();
        return jsonProxyFactoryBean.getObject();
    }
```

It's mainly because this original proxy doesn't support methods of `CompletableFuture ` signature.

**Pull request closed without merging**
