### PR TITLE
fix typo in sample section for readme file

### PR DESCRIPTION
**Pull request by lebron374**
## What is the purpose of the change

fix README.md faile

## Brief changelog
```
public class GreetingsServiceImpl implements GreetingsService {
```
change to

```
public class GreetingServiceImpl implement GreetingService {
```

## Verifying this change

```
public class GreetingsServiceImpl implements GreetingsService {
```
change to

```
public class GreetingServiceImpl implement GreetingService {
```

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues/6246) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by htynkn** [comment]
they are linking to 
+ https://github.com/apache/dubbo-samples/blob/master/java/dubbo-samples-api/src/main/java/org/apache/dubbo/samples/api/GreetingsService.java
+ https://github.com/apache/dubbo-samples/blob/master/java/dubbo-samples-api/src/main/java/org/apache/dubbo/samples/provider/GreetingsServiceImpl.java

**Comment by lebron374** [comment]
> they are linking to
> 
> * https://github.com/apache/dubbo-samples/blob/master/java/dubbo-samples-api/src/main/java/org/apache/dubbo/samples/api/GreetingsService.java
> * https://github.com/apache/dubbo-samples/blob/master/java/dubbo-samples-api/src/main/java/org/apache/dubbo/samples/provider/GreetingsServiceImpl.java

the README.md is in apache/dubbo，but the code is in apache/dubbo-samples
so，i need to create new pr to change the code in apache/dubbo-samples？

**Comment by lebron374** [comment]
> they are linking to
> 
> * https://github.com/apache/dubbo-samples/blob/master/java/dubbo-samples-api/src/main/java/org/apache/dubbo/samples/api/GreetingsService.java
> * https://github.com/apache/dubbo-samples/blob/master/java/dubbo-samples-api/src/main/java/org/apache/dubbo/samples/provider/GreetingsServiceImpl.java

i find the mistake, and i change the some other mistake,please check.

**Comment by htynkn** [comment]
I fixed the mirror issue and merged into master.
Thanks for your contribution

**Pull request merged**
