### PR TITLE
Delete the lock file after metadata store completion

### PR DESCRIPTION
**Pull request by liaozan**

### CODE REVIEW

**Comment by biyuhao** [comment]
Hi liaozan, thanks for your pr. Could you please clarify why we have to do this?
Because it seems ok to persist the lock file.

**Comment by liaozan** [comment]
In dubbo 3.0.5 version, a warn log will appear when starting the project
```java
2022-01-06 00:42:36.564  WARN 22628 o.a.d.r.zookeeper.ZookeeperRegistry      :  [DUBBO] Failed to save registry cache file, will retry, cause: null, dubbo version: 3.0.5, current host: 10.18.0.3

java.nio.channels.OverlappingFileLockException: null
	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107)
	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
	at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:187)
	at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:555)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
I didn’t look into the code in depth
it looks like it’s caused by repeated locks, and I found that the latest master branch [code](https://github.com/apache/dubbo/blob/4cc3b28a3e7e76ce18bb0a6d0fd288ab07dae99a/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java#L182) has been fixed. 
I also saw the same logic in `AbstractMetadataReport`, so I thought it might be a potential problem, so I submitted pr

**Comment by BurningCN** [comment]
> In dubbo 3.0.5 version, a warn log will appear when starting the project
> 
> ```java
> 2022-01-06 00:42:36.564  WARN 22628 o.a.d.r.zookeeper.ZookeeperRegistry      :  [DUBBO] Failed to save registry cache file, will retry, cause: null, dubbo version: 3.0.5, current host: 10.18.0.3
> 
> java.nio.channels.OverlappingFileLockException: null
> 	at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
> 	at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
> 	at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1107)
> 	at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
> 	at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:187)
> 	at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:555)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> ```
> 
> I didn’t look into the code in depth it looks like it’s caused by repeated locks, and I found that the latest master branch [code](https://github.com/apache/dubbo/blob/4cc3b28a3e7e76ce18bb0a6d0fd288ab07dae99a/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java#L182) has been fixed. I also saw the same logic in `AbstractMetadataReport`, so I thought it might be a potential problem, so I submitted pr
> 
> see also this(#9358)

You can look at the `FileCacheStore` of the latest 3.0 code. This file lock will not be released every time it is used up, but will be released when the `FileCacheStore#destroy` method is finally called. You can also refer to the handling of `OverlappingFileLockException` in `FileCacheStore` .

In addition, this exception occurs when two application cache files opened on a machine have the same name, which leads to tryLock on the same file, which triggers this exception. For example, the following two test cases will trigger

image

**Comment by liaozan** [comment]
I just think the behavior of https://github.com/apache/dubbo/blob/4cc3b28a3e7e76ce18bb0a6d0fd288ab07dae99a/dubbo-registry/dubbo-registry-api/src/main/java/org/apache/dubbo/registry/support/AbstractRegistry.java#L182 and https://github.com/apache/dubbo/blob/b65976eca005e21089eb5ac6284314346f3eaef6/dubbo-metadata/dubbo-metadata-api/src/main/java/org/apache/dubbo/metadata/report/support/AbstractMetadataReport.java#L155 should be consistent

**Comment by liaozan** [comment]
any body？

**Pull request closed without merging**
