### PR TITLE
Optimize code in dubbo-common

### PR DESCRIPTION
**Pull request by OLPMO**
in java8,new Method[0] is better than new Method[methods.size()],you can learn about this from the below url:
https://shipilev.net/blog/2016/arrays-wisdom-ancients/

### CODE REVIEW

**Comment by OLPMO** [comment]
I have watched the log of ci,but I did not know how to fix this error.If anyone could tell me what should I  do ,I would be very grateful.

**Comment by lzf971107** [comment]
> I have watched the log of ci,but I did not know how to fix this error.If anyone could tell me what should I do ,I would be very grateful.

Fortunately, he performed correctly in my computer, or you can manually close the pr, reopen the pr, or submit a merge request to reactivate the ci check and try.

**Comment by lndj** [comment]
> in java8,new Method[0] is better than new Method[methods.size()],you can learn about this from the below url:
> https://shipilev.net/blog/2016/arrays-wisdom-ancients/

I have read this article, are you sure new Method[0] is better than new Method[methods.size()]? Maybe you should read it again.

**Comment by OLPMO** [comment]
You can read the following sentences in the conclusion part. @lndj 
Bottom line: **toArray(new T[0]) seems faster, safer, and contractually cleaner, and therefore should be the default choice now.** Future VM optimizations may close this performance gap for toArray(new T[size]), rendering the current "believed to be optimal" usages on par with an actually optimal one. Further improvements in toArray APIs would follow the same logic as toArray(new T[0]) — the collection itself should create the appropriate storage.

**Pull request merged**
