### PR TITLE
log messages support use placeholders and parameters

### LINKED ISSUE #12356: Improve the flexibility and readability of Dubbo logging
## Abstract: 
As a mature micro-service framework, Dubbo has made great achievements in logging. However, the logger implemented by Dubbo only supports the configuration-based method at present, which can't make full use of the placeholder value assignment function provided by the underlying logger. As a result, developers can only use logger.debug(String message) for logging, instead of using more elegant placeholder log printing methods like Spring, Netty, Kubernetes and other projects. In order to improve the flexibility and readability of Dubbo logging, it is suggested to add a conversion layer in the middle of the logger to support placeholder logging.

## Suggestion:
1.Add a conversion layer in the middle of Dubbo's loggers to convert placeholder loggers into formats acceptable to the underlying loggers.
2.Provide an API or configuration item that allows developers to log by using placeholders and parameters, such as logger. debug (string message, object ... params).
3.The logic of formatting and replacing parameter values is realized in the conversion layer to ensure the correctness and readability of log records.

## Example:
The following code snippets demonstrate the difference between the current logging approach and the proposed placeholder-based logging approach after incorporating the conversion layer:

### Current approach:
`logger.debug("Processing request: " + request.getPath() + " from IP: " + request.getRemoteIP());`

### Placeholder-based approach (with conversion layer):
`logger.debug("Processing request: {} from IP: {}", request.getPath(), request.getRemoteIP());`

The placeholder-based logging approach improves code readability and offers greater flexibility for log output. It allows developers to separate the log message template from the parameter values, resulting in more concise and maintainable code.

## Expected Benefits:
Developers can log messages using placeholders and parameters, enabling more flexible and maintainable logging.
Through the conversion layer, Dubbo can adapt to various underlying logging frameworks, providing a consistent logging experience.
Enhance Dubbo's competitiveness in logging capabilities, attracting more developers and organizations to choose Dubbo as a distributed service framework.
This proposal aims to improve the logging functionality of Dubbo, enhancing development experience and code quality. I look forward to discussing and implementing this improvement together with the community.

### PR DESCRIPTION
**Pull request by MartinDai**
## What is the purpose of the change

fixed #12356 

## Brief changelog

log messages support use placeholders and parameters

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
ErrorTypeAwareLogger is also needed

**Review by AlbumenJ — APPROVED** [review]

**Comment by AlbumenJ** [comment]
pls resolve conflicts

**Review by AlbumenJ — APPROVED** [review]

**Comment by AlbumenJ** [comment]
@CrazyHZM PTAL

**Review by AlbumenJ — APPROVED** [review]

**Review by EarthChen — APPROVED** [review]
LGTM

**Pull request merged**
