### PR TITLE
[ISSUE-#7125]  Promise doSubscribe notify and childListen notify synchronize.

### PR DESCRIPTION
**Pull request by horizonzy**
## What is the purpose of the change
Fix-#7125

### CODE REVIEW

**Review by AlbumenJ — APPROVED** [review]
lgtm

**Comment by horizonzy** [comment]
> first put will cause Null Point Exception?

won't

**Comment by horizonzy** [comment]
> first put will cause Null Point Exception?

I remember I modify it. Please view file changes. The second commit already fix it.

**Review by chickenlj — APPROVED** [review]
LGTM

**Pull request merged**
