### PR TITLE
fix:embedded-redis need update version to run on macos Sonoma 

### PR DESCRIPTION
**Pull request by RainYuY**
## What is the purpose of the change

refer:  [#14072 ](https://github.com/apache/dubbo/issues/14072)

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by JavaLionLi** [comment]
兄台 把jedis版本升一升呗 现在用的太低了

**Comment by RainYuY** [comment]
> 兄台 把jedis版本升一升呗 现在用的太低了

Why do we need to upgrade?

**Comment by JavaLionLi** [comment]
> > 兄台 把jedis版本升一升呗 现在用的太低了
> 
> Why do we need to upgrade?

因为性能和bug 新版本性能更好bug更少

**Comment by RainYuY** [comment]
> > > 兄台 把jedis版本升一升呗 现在用的太低了
> > 
> > 
> > Why do we need to upgrade?
> 
> 因为性能和bug 新版本性能更好bug更少

I understand your point, but I believe if there are no actual bugs or security issues, there's no need to update it. However, if you'd like to propose an upgrade, you can open another pull request to discuss it with the community. I think the committers or PMC would appreciate seeing these beneficial changes and review them.

**Comment by AlbumenJ** [comment]
Test pass in https://github.com/Stellar1999/dubbo/actions/runs/8797724351/job/24143774059

**Review by AlbumenJ — APPROVED** [review]

**Pull request merged**
