### PR TITLE
[Dubbo-7406] Fix ServiceCheckUtils.isRegistered not check all registries

### LINKED ISSUE #7406: ServiceCheckUtils.isRegistered not check all registries
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

Dubbo version: 2.7.8
Operating System version: MacOS
Java version: 8
Service register: nacos

### Steps to reproduce this issue

https://github.com/apache/dubbo/blob/2d9583adf26a2d8bd6fb646243a9fe80a77e65d5/dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/ServiceCheckUtils.java#L33-L35
就如TODO注释所言：
判断服务是否注册时候，只判断了一个Registry，会导致判断服务一直未注册。

image

### Scope of influence
影响范围：QOS和Telent中ls命令
https://dubbo.apache.org/zh/docs/v2.7/user/references/qos/
https://dubbo.apache.org/zh/docs/v2.7/user/references/telnet/

### Expected Result

判断多个registries

### PR DESCRIPTION
**Pull request by nickwongwong**
## What is the purpose of the change

Fix #7406

## Brief changelog

dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/ServiceCheckUtils.java

## Verifying this change

Yes.
Before:
image

After:
image

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by xiaoheng1** [comment]
LGTM

**Review by xiaoheng1 — APPROVED** [review]
LGTM

**Comment by AlbumenJ** [comment]
would it be more reasonable to provide three state ( like all registered, some registered, none registered ) ?

**Review by xiaoheng1 — APPROVED** [review]
LGTM

**Comment by AlbumenJ** [comment]
As for current solution, it just check if service has been registered to `at least one` registries. 

But, while some of the registries, this method will directly return `true`.

My question is whether we should provide a state like `none of the registries has been registered`, `some ( or how many ) of the registries has been registered` and `all of the registries has been registered`.

**Comment by xiaoheng1** [comment]
> As for current solution, it just check if service has been registered to `at least one` registries.
> 
> But, while some of the registries, this method will directly return `true`.
> 
> My question is whether we should provide a state like `none of the registries has been registered`, `some ( or how many ) of the registries has been registered` and `all of the registries has been registered`.

In my opinion, service only needs to be registered in a registry, and consumers can call it. We do not need to display the detailed registration information of the provider in the qos list. do you think so ?

**Comment by AlbumenJ** [comment]
@nickwongwong Please fix compile errors

**Comment by nickwongwong** [comment]
I think this is an error caused by other commits?

**Comment by chickenlj** [comment]
Seems like there is compilation error
```java
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/home/runner/work/dubbo/dubbo/dubbo/dubbo-plugin/dubbo-qos/src/main/java/org/apache/dubbo/qos/command/util/ServiceCheckUtils.java:[35,13] error: cannot find symbol
  symbol:   class RegisterStatedURL
  location: class ServiceCheckUtils

    at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute (AbstractCompilerMojo.java:1220)
    at org.apache.maven.plugin.compiler.CompilerMojo.execute (CompilerMojo.java:187)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
```

**Comment by CrazyHZM** [comment]
No feedback for a long time, please close the issue temporarily.

**Pull request closed without merging**
