### PR TITLE
rpc in same zone or rpc in same cell

### PR DESCRIPTION
**Pull request by carlvine500**
## What is the purpose of the change
fix issue: https://github.com/apache/dubbo/issues/12763
### most people depoy service in three zone for HA , we expect service rpc in same zone : 

WeChat59657f69ec05d9cc588af6d033f03e95

tag-subnets:
```
cn|shanghai|a:
- 172.37.66.0/24 #zone=cn-shanghai-a
- 172.37.67.0/24 #zone=cn-shanghai-a
cn|shanghai|b:
- 172.37.68.0/24 #zone=cn-shanghai-b
cn|shanghai|c:
- 172.37.69.0/24 #zone=cn-shanghai-c
```
### some company's service are in a big zone , we expect service rpc in same cell : 
WeChata0d541688dc3fb1b8b84931642e6ad33
tag-subnets:

```
cn|shanghai|a|cell-1:
- 172.31.35.0/24 #zone=cn-shanghai-a
cn|shanghai|a|cell-2:
- 172.31.36.0/24 #zone=cn-shanghai-a
cn|shanghai|a|cell-3:
- 172.31.37.0/24 #zone=cn-shanghai-a
```

### some company's service are in serveral city, we expect service prefer rpc in same zone , and rpc special service across zone( such as stock quantity service): 
WeChatacb485d9d2e4cb56bd50c4f3557e83b4
tag-subnets:

```
cn|shanghai|a:
- 172.37.66.0/24 #zone=cn-shanghai-a
cn|hangzhou|b:
- 172.37.67.0/24 #zone=cn-hangzhou-b
cn|shenzhen|c:
- 172.37.68.0/24 #zone=cn-shenzhen-c
"":
- 172.37.69.0/24 #zone=cn-shanghai-d, as common service
```

## Brief changelog
- add a configuration in configcenter: /dubbo/config/dubbo/tag.subnets , content is :

```
cn|shanghai|a:
- 172.37.66.0/24 #zone=cn-shanghai-a
cn|shanghai|b:
- 172.37.68.0/24 #zone=cn-shanghai-b
cn|shanghai|c:
- 172.37.69.0/24 #zone=cn-shanghai-c
```

- ServiceConfig.java will add a tag by subnet, such as : 
service on host 172.37.66.1 will add a dubbo.tag=cn|shanghai|a

- and then service in cn-shanghai-a will rpc same zone

- pull request https://github.com/apache/dubbo/pull/12673 will help to prefer rpc with long tag-level, for example:
consumer    rpc tag=cn|shanghai|a
prefer1: service tag=cn|shanghai|a 
prefer2: service tag=cn|shanghai
prefer3: service tag=cn
prefer4: service tag=""

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by AlbumenJ — COMMENTED** [review]
Seems like a dynamic tag service?

**Comment by carlvine500** [comment]
> Yes! subnets( 172.37.66.0/24,172.37.67.0/24) , they are allocated with zone in aws-VPC or aliyun-VPC , dubbo will generate a tag by these subnets .
> 
> some developer can debug these tag in a zone , eg: dubbo.tag=cn|shanghai|a|cell-1 .
> 
> developer in our company always forget to start dubbo with tag , we can add a default tag by subnet(192.168.0.0/16) .

Yes!
subnets( 172.37.66.0/24,172.37.67.0/24) , they are allocated with zone in aws-VPC or aliyun-VPC ,
dubbo will generate a tag by these subnets .

some developer can debug these tag in a zone , eg: dubbo.tag=cn|shanghai|a|cell-1 .

developer in our company always forget to start dubbo with tag , we can add a default tag by subnet(192.168.0.0/16) .

**Comment by AlbumenJ** [comment]
Can this be split into an independent module in dubbo-spi-extensions?

**Comment by carlvine500** [comment]
> Can this be split into an independent module in dubbo-spi-extensions?

OK , I will try to refactor  .

**Comment by carlvine500** [comment]
this pull request was migrated to dubbo-spi-extensions: 
[216](https://github.com/apache/dubbo-spi-extensions/pull/216)

**Comment by AlbumenJ** [comment]
Let's working on https://github.com/apache/dubbo-spi-extensions/pull/216

**Pull request closed without merging**
