### PR TITLE
[Dubbo-6020] fixbug getServiceDefinition get serviceInterface,group and version error.

### PR DESCRIPTION
**Pull request by drow931**
## What is the purpose of the change

bugfix method RemoteMetadataServiceProxy#getServiceDefinition.

## Brief changelog

get serviceInterface,group and version from UrlUtils.parseServiceKey results

## Verifying this change

run test method org.apache.dubbo.registry.client.metadata.proxy.RemoteMetadataServiceProxyTest#testGetServiceDefinition

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [x] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by zonghaishang** [comment]
It looks good to me.

**Comment by zonghaishang** [comment]
@chickenlj please take a look.

**Comment by drow931** [comment]
@chickenlj

**Comment by AlbumenJ** [comment]
@drow931 hi, thanks for your contribution.

Currently, `RemoteMetadataServiceProxy` has been removed for new Service-Discovery model reformation.

Related source code is no longer existed in the latest version of master branch.

Please feel free to reopen this pr if you still have any question, also you can create a new pr for related code.

**Pull request closed without merging**
