### PR TITLE
[3.0] upgrade pom version

### PR DESCRIPTION
**Pull request by wangchengming666**
upgrade pom version

### CODE REVIEW

**Comment by guohao** [comment]
versions in dependency modules also need update :D

**Comment by wangchengming666** [comment]
> versions in dependency modules also need update :D

已经更新过啦😄

**Comment by guohao** [comment]
> > versions in dependency modules also need update :D
> 
> 已经更新过啦😄

Will be merged after 3.0.7 released

**Comment by chickenlj** [comment]
Sorry, this patch will be conflicted with 3.0.7-release. So we have to close it.

**Pull request closed without merging**
