### PR TITLE
Remove impossible reach branch and the useless variable.

### PR DESCRIPTION
**Pull request by Chiyuxing**
## What is the purpose of the change

1. Clean code.
2. Improve performence.

## Brief changelog

Remove the useless variable `success` and the associated unreachable branche.

## Verifying this change

Build and Tested

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by leechor** [comment]
LGTM

**Comment by htynkn** [comment]
I believe doUnregister method and doSubscribe method may has similar issue. Could you please help to check and include them in this PR?

**Comment by leechor** [comment]
> I believe doUnregister method and doSubscribe method may has similar issue. Could you please help to check and include them in this PR?

no problem! I do it just later.

**Comment by Chiyuxing** [comment]
> I believe doUnregister method and doSubscribe method may has similar issue. Could you please help to check and include them in this PR?

With pleasure.

**Comment by Chiyuxing** [comment]
@htynkn I have done. Pls review it again.

**Review by htynkn — APPROVED** [review]

**Comment by htynkn** [comment]
I did some small change to revert some unrelated code format.
Your PR has been merge into master branch now. Thanks for your contribution

**Comment by Chiyuxing** [comment]
> I did some small change to revert some unrelated code format.
> Your PR has been merge into master branch now. Thanks for your contribution

Great. Thanks for your assistance.

**Pull request merged**
