### PR TITLE
Including setup method to clean state between tests

### PR DESCRIPTION
**Pull request by odrepa**
## What is the purpose of the change
In InternalThreadLocalTest, testSize fails when run after testSetAndGet, testRemove, or testRemoveAll in the same test class. I found that running InternalThreadLocalMap.remove() before testSize ensures the starting state is correct such that testSize can pass even when run after those three tests. I introduced the setup method to ensure this resetting logic is run before each test. Please let me know if there is a more preferred way to address this issue.

## Brief changelog
Including a setup method that sets the state through InternalThreadLocalMap.remove().

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by BurningCN** [comment]
hi, why my local test did not reproduce
image

**Comment by odrepa** [comment]
Hi,

Sorry for the late response. On my side, what I could to reproduce the failure in the specific order is to add the annotation "@org.junit.jupiter.api.TestMethodOrder(org.junit.jupiter.api.MethodOrderer.Alphanumeric.class)" to the test class (as to force alphabetical test method order, which would put testSize at the end), leading to testSize to fail. The failure message I would see is:

```
org.opentest4j.AssertionFailedError: size method is wrong! ==> expected: <1> but was: <4>
        at org.apache.dubbo.common.threadlocal.InternalThreadLocalTest.testSize(InternalThreadLocalTest.java:78)
```

**Review by BurningCN — APPROVED** [review]
LGTM

**Comment by BurningCN** [comment]
Without the `TestMethodOrder` annotation, my side has always been normal.
But as far as this `pr` is concerned, I think it’s good to do a pre-cleaning operation before each test.

**Comment by odrepa** [comment]
As per the suggestion, I've switched to using `@AfterEach` to clean up instead of setting up.

**Pull request merged**
