### PR TITLE
Optimizing issue 6095

### PR DESCRIPTION
**Pull request by brucelwl**
Optimizing issue https://github.com/apache/dubbo/issues/6095

### CODE REVIEW

**Comment by superleo-cn** [comment]
I think it's a duplicated issue for #6094. Once you get the work done, the issue also can be closed.

**Comment by brucelwl** [comment]
> I think it's a duplicated issue for #6094. Once you get the work done, the issue also can be closed.

完全不一样的问题

**Comment by superleo-cn** [comment]
> > I think it's a duplicated issue for #6094. Once you get the work done, the issue also can be closed.
> 
> 完全不一样的问题

Sorry, it's my mistake. I misread the title of the issue.

**Comment by mercyblitz** [comment]
Please merge the latest code in the master branch.

**Pull request closed without merging**
