### PR TITLE
Dubbo-upgrade netty4 version to 4.1.42

### PR DESCRIPTION
**Pull request by Moriadry**
## What is the purpose of the change

Netty before 4.1.42.Final mishandles whitespace before the colon in HTTP headers (such as a "Transfer-Encoding : chunked" line), which leads to HTTP request smuggling.

## Brief changelog

upgrade netty version and a minor format

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by htynkn** [comment]
[INFO] Running org.apache.dubbo.remoting.etcd.jetcd.JEtcdClientTest
[WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0 s - in org.apache.dubbo.remoting.etcd.jetcd.JEtcdClientTest
[INFO] Running org.apache.dubbo.remoting.etcd.jetcd.LeaseTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
        â„¹ï¸Ž Checking the system...
        âœ” Docker version should be at least 1.6.0
        âœ” Docker environment should have more than 2GB free disk space
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[ERROR] Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 11.779 s <<< FAILURE! - in org.apache.dubbo.remoting.etcd.jetcd.LeaseTest
[ERROR] testGrant  Time elapsed: 0.494 s  <<< ERROR!
java.lang.RuntimeException: Cannot create Epoll EventLoopGroup
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)
Caused by: java.lang.reflect.InvocationTargetException
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)
Caused by: java.lang.NoSuchMethodError: io.netty.channel.SingleThreadEventLoop.<init>(Lio/netty/channel/EventLoopGroup;Ljava/util/concurrent/Executor;ZLjava/util/Queue;Ljava/util/Queue;Lio/netty/util/concurrent/RejectedExecutionHandler;)V
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)

[ERROR] testKeepAlive  Time elapsed: 0.006 s  <<< ERROR!
java.lang.RuntimeException: Cannot create Epoll EventLoopGroup
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)
Caused by: java.lang.reflect.InvocationTargetException
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)
Caused by: java.lang.NoSuchMethodError: io.netty.channel.SingleThreadEventLoop.<init>(Lio/netty/channel/EventLoopGroup;Ljava/util/concurrent/Executor;ZLjava/util/Queue;Ljava/util/Queue;Lio/netty/util/concurrent/RejectedExecutionHandler;)V
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)

[ERROR] testKeepAliveOnce  Time elapsed: 0.003 s  <<< ERROR!
java.lang.RuntimeException: Cannot create Epoll EventLoopGroup
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)
Caused by: java.lang.reflect.InvocationTargetException
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)
Caused by: java.lang.NoSuchMethodError: io.netty.channel.SingleThreadEventLoop.<init>(Lio/netty/channel/EventLoopGroup;Ljava/util/concurrent/Executor;ZLjava/util/Queue;Ljava/util/Queue;Lio/netty/util/concurrent/RejectedExecutionHandler;)V
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)

[ERROR] testRevoke  Time elapsed: 0.005 s  <<< ERROR!
java.lang.RuntimeException: Cannot create Epoll EventLoopGroup
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)
Caused by: java.lang.reflect.InvocationTargetException
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)
Caused by: java.lang.NoSuchMethodError: io.netty.channel.SingleThreadEventLoop.<init>(Lio/netty/channel/EventLoopGroup;Ljava/util/concurrent/Executor;ZLjava/util/Queue;Ljava/util/Queue;Lio/netty/util/concurrent/RejectedExecutionHandler;)V
	at org.apache.dubbo.remoting.etcd.jetcd.LeaseTest.setUp(LeaseTest.java:89)

**Comment by htynkn** [comment]
https://api.travis-ci.org/v3/job/640007438/log.txt

**Comment by chickenlj** [comment]
Please, check the failed UTs first.

**Comment by Moriadry** [comment]
@htynkn @chickenlj  Sorry for missing that, will fix it ASAP.

**Comment by chickenlj** [comment]
Is API of 4.1.42 guaranteed to be compatible with that of 4.1.25?

**Comment by chickenlj** [comment]
I wonder if this upgrade will have a breaking impact on end-users as Netty is usually a base component for most projects and middleware frameworks.

**Comment by Moriadry** [comment]
@chickenlj 

`Netty before 4.1.42.Final mishandles whitespace before the colon in HTTP headers (such as a "Transfer-Encoding : chunked" line), which leads to HTTP request smuggling.` This is warning from github, and it seems Netty before 4.1.42 got serious bug, and may cause some certain error. Since checks are all passed,  we can take this as Step one to ensure both versions are compatible?

**Pull request closed without merging**
