### PR TITLE
Migrate tests to JUnit5

### PR DESCRIPTION
**Pull request by strangelookingnerd**
Most of the tests already use JUnit5. This PR will migrate the missing tests and remove the `junit-jupiter-vintage` as well as `junit` dependencies.

Migration includes:

* Using JUnit5 annotations
* Using `Assertions` 
* Remove `public` modifiers from test classes and methods
* Clean up assertions (switching `expected` and `actual`, simplyifing assertions...)
* Trivial code cleanup

I validated my changes using `./build -t`.

## Checklist
- [ ] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Make sure gitHub actions can pass. [Why the workflow is failing and how to fix it?](./CONTRIBUTING.md)

### CODE REVIEW

**Comment by wcy666103** [comment]
LGTM

**Comment by wcy666103** [comment]
Test locally first.

image

**Comment by strangelookingnerd** [comment]
> Test locally first.

Seems like I missed that one, sorry for that. However to me it seems like this test should have failed without my changes as well.

I noticed that there is an exact copy of the failing test which has the assertion that is causing the issue here is commented out

Comparing 
[dubbo-spring-boot/src/test/java/org/apache/dubbo/spring/boot/env/DubboDefaultPropertiesEnvironmentPostProcessorTest.java](https://github.com/strangelookingnerd/dubbo/blob/757dd4bfd73df36f9f9a85caa314a5b93a066efe/dubbo-spring-boot-project/dubbo-spring-boot/src/test/java/org/apache/dubbo/spring/boot/env/DubboDefaultPropertiesEnvironmentPostProcessorTest.java#L58)

[dubbo-spring-boot-autoconfigure/src/test/java/org/apache/dubbo/spring/boot/env/DubboDefaultPropertiesEnvironmentPostProcessorTest](https://github.com/strangelookingnerd/dubbo/blob/757dd4bfd73df36f9f9a85caa314a5b93a066efe/dubbo-spring-boot-project/dubbo-spring-boot-autoconfigure/src/test/java/org/apache/dubbo/spring/boot/env/DubboDefaultPropertiesEnvironmentPostProcessorTest.java#L58)

---

**Edit:**

I just confirmed that the test that is failing was simply not executed before my changes. Digging a little deeper I found #12861 which suggests that the property that is checked here caused some kind of issue. I therefore propose to give the test the same treatment as in `dubbo-spring-boot` and comment the assertion out.

**Review by CrazyHZM — APPROVED** [review]
LGTM

**Pull request merged**
