### PR TITLE
refine checkstyle

### PR DESCRIPTION
**Pull request by XenoAmess**
## What is the purpose of the change

add checkstyles to make sure there be no crlf file.

if the build fails, then the checkstyles works.

simple and easy.

...I can find some time to fix all these checkstyles for you but I want to know about your opinions first.

## Verifying this change

- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by AlbumenJ** [comment]
@XenoAmess For lineSeparator I think we should discuss in mailing list(dev@dubbo.apache.org) first.

Also, for now, you can reopen the previous PRs about code style. I am sorry for keeping you waiting so long.

**Comment by chickenlj** [comment]
Let's do this on the 3.0 branch.

**Comment by chickenlj** [comment]
Thank you @XenoAmess , please see this patch https://github.com/apache/dubbo/pull/8019 Albumen added to 3.0.

**Comment by XenoAmess** [comment]
> Thank you @XenoAmess , please see this patch #8019 Albumen added to 3.0.

got it.
looks good.
thanks.

**Pull request closed without merging**
