### PR TITLE
[Dubbo-4588]block the zookeeper connect process util the connection is established

### LINKED ISSUE #4588: Zookeeper registry will hang the main thread if it cannot establish to the zookeeper register center
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.4-SNAPSHOT
* Operating System version: Mac
* Java version: java11

### Steps to reproduce this issue

1. config in xml like (other config keep the same as the previous version)
```xml
<dubbo:registry address="zookeeper://127.0.0.2:2181"/>

<dubbo:config-center address="zookeeper://127.0.0.1:2181"/>
```
2. start the provider application

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

The application can log exception and exit

### Actual Result

it will hang the main thread in the method of ZookeeperRegistry.java
```java
    @Override
    public void doRegister(URL url) {
        try {
            zkClient.create(toUrlPath(url), url.getParameter(DYNAMIC_KEY, true));
        } catch (Throwable e) {
            throw new RpcException("Failed to register " + url + " to zookeeper " + getUrl() + ", cause: " + e.getMessage(), e);
        }
    }
```

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

### PR DESCRIPTION
**Pull request by tswstarplanet**
## What is the purpose of the change

fix #4588

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by beiwei30** [comment]
@tswstarplanet pls. take a look at https://github.com/apache/dubbo/pull/4582, will it solve the same problem?

**Comment by tswstarplanet** [comment]
> @tswstarplanet pls. take a look at #4582, will it solve the same problem?

@beiwei30 If user config different zookeeper addresses for config center and register center, and the config center address is right but the register center address is wrong, there will be a problem.

**Comment by beiwei30** [comment]
I don't agree with ur solution. We may need to consider this:

```java
            client.start();
            boolean connected = client.blockUntilConnected(timeout, TimeUnit.MILLISECONDS);
            if (!connected) {
                throw new IllegalStateException("not connected");
            }
```

**Comment by tswstarplanet** [comment]
> I don't agree with ur solution. We may need to consider this:
> 
> ```java
> client.start();
> boolean connected = client.blockUntilConnected(timeout, TimeUnit.MILLISECONDS);
> if (!connected) {
>     throw new IllegalStateException("not connected");
> }
> ```
@beiwei30 
Yes, this is my first implementation. I have found its problem. And I have commit amend new implementation. Please have a look at the final version of code.

**Comment by tswstarplanet** [comment]
> I don't agree with ur solution. We may need to consider this:
> 
> ```java
> client.start();
> boolean connected = client.blockUntilConnected(timeout, TimeUnit.MILLISECONDS);
> if (!connected) {
>     throw new IllegalStateException("not connected");
> }
> ```

@beiwei30 Yes, I agree to that ur solution is better.

**Pull request merged**
