### PR TITLE
Feature metrics support otlp

### PR DESCRIPTION
**Pull request by glmapper**
optimized for #13902

### CODE REVIEW

**Review by songxiaosheng — APPROVED** [review]
LGTM

**Comment by songxiaosheng** [comment]
Can we add a case to the dubbo sample repository

**Comment by glmapper** [comment]
> Can we add a case to the dubbo sample repository
Okay

**Comment by AlbumenJ** [comment]
Please merge into 3.3 branch

**Comment by glmapper** [comment]
> Please merge into 3.3 branch

https://github.com/apache/dubbo/pull/14067

**Comment by AlbumenJ** [comment]
Track in https://github.com/apache/dubbo/pull/14067

**Pull request closed without merging**
