### PR TITLE
Fix issue #8541 on branch master

### PR DESCRIPTION
**Pull request by BazookaW**
issue no #8541

### CODE REVIEW

**Review by changfubai — APPROVED** [review]
LGTM

**Review by xiaoheng1 — COMMENTED** [review]
In what scenario did you report the error, can you post the configuration? My local test found it to be normal

**Comment by AlbumenJ** [comment]
It might not a good idea to add such timestamp key on provider url. For Service Discovery model, we treat a group of providers which provide the same services have the same urls. This need these providers' urls do not contains dynamic keys like `timestamp`.

**Comment by yuanhe3** [comment]
> It might not a good idea to add such timestamp key on provider url. For Service Discovery model, we treat a group of providers which provide the same services have the same urls. This need these providers' urls do not contains dynamic keys like `timestamp`.

你好，请教下，我遇到一个问题，就是我在dubbo的服务端的xml 配置了parameter 参数，这个参数我设置的是动态key如timestamp，之后我通过消费端调用服务端的接口，因为我服务端部署了两个实例，这样的话，我理解在消费端拿到的服务端的 timestamp 应该就是不同的，但是我测试后，发现消费端调用的两个服务端实例的 timestamp 都是相同的（取的是其中一个服务端实例的参数），这个是不是你说的Service Discovery mode 导致的呢，是不是有在某个环节把这些参数都默认取其中一个服务端实例的参数呢？

**Pull request closed without merging**
