### PR TITLE
Fix consumer can not get server attachment info with using explicit-target(#7937)

### PR DESCRIPTION
**Pull request by mr3**
## What is the purpose of the change
Fix issue[#7937]

## Brief changelog

This commit will **repeated set** when service registry discovery, maybe there shoule be a better way, pls reply me ASAP.
`ConsumerContextFilter.onResponse`
`ConsumerContextClusterInterceptor.onMessage`

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by AlbumenJ** [comment]
I think it would be better to move ConsumerContextClusterInterceptor back to Filter. ClusterInterceptor is deprecated in Dubbo 3, and be replaced with ClusterFilter.

**Comment by mr3** [comment]
If move `ConsumerContextClusterInterceptor` back to Filter, is `ConsumerContextFilter` or `ConsumerContextClusterInterceptor` duplicated?  

We have added it a filter(be activated with parameter) to fix this.

What is the `ConsumerContextClusterInterceptor` class used for?  Multi registry or what else?

**Comment by AlbumenJ** [comment]
> If move `ConsumerContextClusterInterceptor` back to Filter, is `ConsumerContextFilter` or `ConsumerContextClusterInterceptor` duplicated?
> 
> We have added it a filter(be activated with parameter) to fix this.
> 
> What is the `ConsumerContextClusterInterceptor` class used for? Multi registry or what else?

just remove `ConsumerContextClusterInterceptor`

**Comment by mr3** [comment]
@AlbumenJ  pls see [PR-8024](https://github.com/apache/dubbo/pull/8024) and close this, thanks.

**Pull request closed without merging**
