### PR TITLE
[Dubbo-4771]fix protocol register set false not work

### LINKED ISSUE #4771: dubbo:protocol register attribute not work
### Environment

* Dubbo version: 2.7.3
* Operating System version: CentOS7
* Java version: 1.8

### Steps to reproduce this issue

1. Set two protocal, with different "register" attribute

```xml
<dubbo:protocol name="dubbo" port="8751" register="true"  />
<dubbo:protocol name="hessian" port="8752" register="false" />
```

2. use the zookeeper registry center

```xml
<dubbo:registry address="..." file="./.dubbo_cache" />
```

3. start the server and view the provider in zkCli

### Expected Result
only the dubbo is registed

### Actual Result
the dubbo and hession protocol are registed

### PR DESCRIPTION
**Pull request by tswstarplanet**
## What is the purpose of the change

fix #4771

## Brief changelog

AbstractServiceConfig.java

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by AnthonyKot** [comment]
Don't think it actually change something. Now we have all services configured with register=false by default. Soon there is no filter for skipping the registration based on property set we have this:

[DUBBO] Register dubbo service org.apache.dubbo.samples.api.GreetingService url hessian://172.25.26.102:20881/org.apache.dubbo.samples.api.GreetingService?blalbla&**[register=false]**&release=2.7.4-SNAPSHOT&revision=1.0.0&balblablabla, dubbo version: 2.7.4-SNAPSHOT, current host: 172.25.26.102

As you can see service has register set to false but anyway it was registered.

**Comment by tswstarplanet** [comment]
@AnthonyKot You can pull my branch and test, it works even though the log print register. I think it's a problem about the log.

**Comment by tswstarplanet** [comment]
> @AnthonyKot You can pull my branch and test, just watch the zookeeper if the service is registered. It works even though the log print register. I think it's a problem about the log.

**Comment by tswstarplanet** [comment]
@AnthonyKot I test it again and it works. You can watch the zookeeper if the service is registered. I think it's just the log has an error.

**Pull request merged**
