### PR TITLE
[ISSUE-#7722] Fix serviceNameMapping didn't work problem.

### PR DESCRIPTION
**Pull request by horizonzy**
## What is the purpose of the change
For-#7722

### CODE REVIEW

**Review by xiaoheng1 — COMMENTED** [review]
if (SERVICE_REGISTRY_PROTOCOL.equals(registryURL.getProtocol())) {
                            url = url.addParameterIfAbsent(REGISTRY_TYPE_KEY, SERVICE_REGISTRY_TYPE);
                        }


Why do we need this paragraph of judgment? In the org.apache.dubbo.config.utils.ConfigValidationUtils#loadRegistries method, it has been converted to registryProtcol based on the registry-type parameter.

**Comment by horizonzy** [comment]
The url is different. 
In method exported.
```
        List<URL> exportedURLs = this.getExportedUrls();
        exportedURLs.forEach(url -> {
            // dubbo2.7.x does not register serviceNameMapping information with the registry by default.
            // Only when the user manually turns on the service introspection, can he register with the registration center.
            boolean isServiceDiscovery = SERVICE_REGISTRY_PROTOCOL.equals(url.getProtocol());
            if (isServiceDiscovery) {
                Map<String, String> parameters = getApplication().getParameters();
                ServiceNameMapping.getExtension(parameters != null ? parameters.get(MAPPING_KEY) : null).map(url);
            }
        });
```
getExportedUrls return the url which didn't hold registry param. 

see:
https://github.com/apache/dubbo/blob/18c5b4cd78bd988fb24c7e570418e542cf45d6bd/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java#L348

**Comment by xiaoheng1** [comment]
> The url is different.
> In method exported.
> 
> ```
>         List<URL> exportedURLs = this.getExportedUrls();
>         exportedURLs.forEach(url -> {
>             // dubbo2.7.x does not register serviceNameMapping information with the registry by default.
>             // Only when the user manually turns on the service introspection, can he register with the registration center.
>             boolean isServiceDiscovery = SERVICE_REGISTRY_PROTOCOL.equals(url.getProtocol());
>             if (isServiceDiscovery) {
>                 Map<String, String> parameters = getApplication().getParameters();
>                 ServiceNameMapping.getExtension(parameters != null ? parameters.get(MAPPING_KEY) : null).map(url);
>             }
>         });
> ```
> 
> getExportedUrls return the url which didn't hold registry param.
> 
> see:
> https://github.com/apache/dubbo/blob/18c5b4cd78bd988fb24c7e570418e542cf45d6bd/dubbo-config/dubbo-config-api/src/main/java/org/apache/dubbo/config/ServiceConfig.java#L348

i get it. you are right.

**Review by xiaoheng1 — APPROVED** [review]
LGTM

**Review by AlbumenJ — APPROVED** [review]

**Pull request merged**
