### PR TITLE
[dubbo-5971]fix tag router override issue #5972

### PR DESCRIPTION
**Pull request by zhouhaopeng**
## What is the purpose of the change

fix tag router select wrong provider issue and delay export test delay time
fix-#5971

## Brief changelog

org.apache.dubbo.rpc.cluster.support.ClusterUtils#mergeUrl
org.apache.dubbo.config.ServiceConfigTest#testDelayExport

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by cvictory** [comment]
@zhouhaopeng  There is some failed at the ci progress.

**Comment by zhouhaopeng** [comment]
> 感觉这个逻辑不对，不应该去修改providerUrl，应该去修改consumerUrl的值。
> 
> 应该修改org.apache.dubbo.registry.integration.RegistryDirectory#mergeUrl， 对overrideDirectoryUrl的赋值过程修改。 过滤掉providerUrl的Tag_key参数。
> 
> org.apache.dubbo.registry.integration.RegistryDirectory#overrideDirectoryUrl

去掉这个remove，就是为了让providr端的tag覆盖consuemr端的配置

**Comment by cvictory** [comment]
@zhouhaopeng ci没通过啊。

**Comment by cvictory** [comment]
暂时先关闭，如果有疑问可以重新reopen下

**Comment by 24kpure** [comment]
> > 感觉这个逻辑不对，不应该去修改providerUrl，应该去修改consumerUrl的值。
> > 应该修改org.apache.dubbo.registry.integration.RegistryDirectory#mergeUrl， 对overrideDirectoryUrl的赋值过程修改。 过滤掉providerUrl的Tag_key参数。
> > org.apache.dubbo.registry.integration.RegistryDirectory#overrideDirectoryUrl
> 
> 去掉这个remove，就是为了让providr端的tag覆盖consuemr端的配置

Is provider tag config overriding consumer's  a best choice? In my opinion, consumer keeping no tag config  is better in some case that  just few provider set tag for test or other special purpose.
Thanks for your answer!

**Comment by zhouhaopeng** [comment]
[image: image.png]
 official document show provider config has a higher priority than
consumer side.

lmj <notifications@github.com> 于2020年9月15日周二 上午9:45写道：

**Comment by zhouhaopeng** [comment]
official document show consumer config has a higher priority than provider
side.

hp zh <haopengzhou.coke@gmail.com> 于2020年9月15日周二 下午5:29写道：

**Pull request closed without merging**
