### PR TITLE
feat: add springboot-starter for nacos and zookeeper

### PR DESCRIPTION
**Pull request by conghuhu**
## What is the purpose of the change

Previously, Dubbo used to dependency on the introduction of `dubbo-dependencies-zookeeper` or `dubbo-dependencies-zookeeper-curator5` for dependency transfer.
 
In the SpringBoot ecosystem, developers were more likely to understand starters rather than dependencies.

## Brief changelog

- add dubbo-nacos-spring-boot-starter
- add dubbo-zookeeper-spring-boot-starter
- add dubbo-zookeeper-curator5-spring-boot-starter

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by conghuhu** [comment]
@chickenlj PTAL

**Review by chickenlj — APPROVED** [review]
LGTM.

**Comment by chickenlj** [comment]
The naming convention of these starters seems different, there are:
`dubbo-zookeeper-spring-boot-starter` and `dubbo-spring-boot-tracing-xxx-starter`.

**Comment by conghuhu** [comment]
Yes, there was some problems with the naming of the previous tracing related starter. Spring officially recommends that the custom starter be named `xxx-spring-boot-starter`.

image

**Comment by chickenlj** [comment]
> 

I think we should change those observability starters to match the Spring official naming convention.

**Comment by chickenlj** [comment]
```java
Error:  Tests run: 10, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.056 s <<< FAILURE! - in org.apache.dubbo.metrics.aggregate.SlidingWindowTest
Error:  org.apache.dubbo.metrics.aggregate.SlidingWindowTest.testCurrentPane  Time elapsed: 0.007 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <org.apache.dubbo.metrics.aggregate.Pane@7eaa2bc6> but was: <org.apache.dubbo.metrics.aggregate.Pane@42d9e8d2>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1142)
	at org.apache.dubbo.metrics.aggregate.SlidingWindowTest.testCurrentPane(SlidingWindowTest.java:50)
```

There are test failures but I don't think it's caused by changes in this pull request.

**Pull request merged**
