### PR TITLE
[Dubbo-6470] Fix NPE and remove try/catch block in NetUtils

### LINKED ISSUE #6470: Fix NPE and remove try/catch block in NetUtils

### PR DESCRIPTION
**Pull request by Technoboy-**
Fix #6470

### CODE REVIEW

**Comment by carryxyh** [comment]
Can you describe what causes NPE to happen? Use unit test to reproduce maybe a better way.

**Comment by Technoboy-** [comment]
> Can you describe what causes NPE to happen? Use unit test to reproduce maybe a better way.

findNetworkInterface may return null.
UT is difficult to write for findNetworkInterface, it depends on environment.
You can find NetUtils has no UT for findNetworkInterface

**Comment by carryxyh** [comment]
Hi, it seems to be difficult to reproduce this problem.

But I think we should make sure that this is indeed a problem before we try to fix it. Have you encountered this problem in a production environment? Can you post your stack?

If it is only for return value verification, then I tend not to merge it, which will cause our submission records to be messy...

**Comment by Technoboy-** [comment]
> messy

So why don't you add UT for findNetworkInterface? 
From the respect of code reviewing, findNetworkInterface may return null.  If nothing happens, why you add try-catch, could please explain, which kind of exception you wanna catch ?  Do you also encounter some problem in a production and let you catch the exception ?

**Comment by Technoboy-** [comment]
> Hi, it seems to be difficult to reproduce this problem.
> 
> But I think we should make sure that this is indeed a problem before we try to fix it. Have you encountered this problem in a production environment? Can you post your stack?
> 
> If it is only for return value verification, then I tend not to merge it, which will cause our submission records to be messy...

So why don't you add UT for findNetworkInterface?
From the respect of code reviewing, findNetworkInterface may return null. If nothing happens, why you add try-catch, could please explain, which kind of exception you wanna catch ? Do you also encounter some problem in a production and let you catch the exception ?

**Comment by Technoboy-** [comment]
cc @CalvinKirs

**Pull request closed without merging**
