### PR TITLE
Optimize code where feasible

### PR DESCRIPTION
**Pull request by OLPMO**
When I view source code, I found that many places can be optimized.So, I submit this pr.

### CODE REVIEW

**Comment by leechor** [comment]
LGTM.

**Comment by OLPMO** [comment]
Has this PR been merged? @leechor @lovepoem

**Comment by lovepoem** [comment]
No, it is not merged

**Comment by OLPMO** [comment]
My old repo has been deleted. But I copy these changes to my new repo and I submit a new pr.
https://github.com/apache/dubbo/pull/5597

**Pull request closed without merging**
