### PR TITLE
Task #13958 Move Rest Protocol to SPI Extensions

### PR DESCRIPTION
**Pull request by wcy666103**
## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by wcy666103** [comment]
There are three things to note:
1. I deleted rest related classes from `dubbo-compatible ` module because they are hard dependencies
2. The `dubbo-plugin/dubbo-rest-jaxrs` module and the test case in the `dubbo-rest-spring` module are all annotated with disable. Consider moving to `apache/dubbo-integration-cases` , as they are compatibility tests
3. The `dubbo - config - spring` module under `ControllerServiceConfigTest` was disable comments, because it is specifically for rest Protocol test cases, considered to be deleted or changed

What should I do about these problems?

**Comment by wcy666103** [comment]
After discussion, it is appropriate to move these three tests to `apache/dubbo-integration-cases`. Thanks for your help @oxsean

**Comment by chickenlj** [comment]
@wcy666103 Too many things are included in one single pull request, better only include one thing each time.

**Comment by wcy666103** [comment]
> @wcy666103 Too many things are included in one single pull request, better only include one thing each time.
Ok, I'll take them apart

**Comment by wcy666103** [comment]
PTAL @chickenlj @songxiaosheng @AlbumenJ

**Comment by songxiaosheng** [comment]
please resolve conflicts

**Review by songxiaosheng — APPROVED** [review]
LGTM

**Comment by songxiaosheng** [comment]
@AlbumenJ  dubbo-samples-test-13787 test failed ,help check

**Pull request merged**
