### PR TITLE
Update DubboCodec.java

### PR DESCRIPTION
**Pull request by linhuaichuan**
## 
fix issue #3537: 新旧版本兼容问题 
## Brief changelog
dubbo 反序列化对分片流操作时的兼容性支持
## Verifying this change
1、DubboCodec 解码时，对is流进行多次操作
              
                ObjectInput in = CodecSupport.deserialize(channel.getUrl(), is, proto);
                if (status == Response.OK) {
                    Object data;
                    if (res.isHeartbeat()) {
                        data = decodeHeartbeatData(channel, in);
                    } else if (res.isEvent()) {
                        data = decodeEventData(channel, in);
                    } else {
                        DecodeableRpcResult result;
                        if (channel.getUrl().getParameter(
                                Constants.DECODE_IN_IO_THREAD_KEY,
                                Constants.DEFAULT_DECODE_IN_IO_THREAD)) {
                            result = new DecodeableRpcResult(channel, res, is,
                                    (Invocation) getRequestData(id), proto);
                            result.decode();
                        } else {
                            result = new DecodeableRpcResult(channel, res,
                                    new UnsafeByteArrayInputStream(readMessageData(is)),
                                    (Invocation) getRequestData(id), proto);
                        }
                        data = result;
                    }
                    res.setResult(data);

2、当序列化工具使用分片读取is时，将造成result.decode()解码错误;比如fst.

### CODE REVIEW

**Comment by lovepoem** [comment]
@linhuaichuan  Can you please add some unit test or integration test to verify the change ?

**Comment by linhuaichuan** [comment]
1、CodecSupport.deserialize 反序列化 is ，当序列化工具使用分片读流时，当RpcResult序列化byte大于分片值时，将引起is的startIndex变动。比如fst工具：org.nustaq.serialization.util.FSTInputStream 默认使用 8000 byte读取is。
2、result.decode() 也是使用CodecSupport来反序列is。若startIndex产生变动，将引起RpcResult 读取带序列化byte不正确。最终可能产生 #3537 bug。

**Comment by limingwei** [comment]
哇哈哈
所以
要解决了么？
什么时候发？

**Comment by beiwei30** [comment]
this change looks reasonable, but it will not solve issue #3537.

**Comment by beiwei30** [comment]
I will port your change into main trunk with this: https://github.com/apache/incubator-dubbo/issues/3991. Once it's in, I will merge your change too. @linhuaichuan

**Comment by qixiaobo** [comment]
The same issue with https://github.com/apache/dubbo/issues/4612
Why nobody take care of old stable version ?

**Comment by qixiaobo** [comment]
Another place also has this code
Why not modify all?

**Comment by AlbumenJ** [comment]
@linhuaichuan hi, thanks for your contribution

pls resolve conflicts with the latest master branch

**Comment by AlbumenJ** [comment]
Close for long time no response.
Please feel free to reopen if you have any question.

**Pull request closed without merging**
