### PR TITLE
optimize #5623 : optimize compatible solution of filter listener

### PR DESCRIPTION
**Pull request by RojerAlone**
## What is the purpose of the change

optimize #5623

### CODE REVIEW

**Comment by RojerAlone** [comment]
@chickenlj

**Comment by chickenlj** [comment]
I would suggest removing `onMessage` completely in the next version.

2.7.5 is not a stable version in our release plan, as stated here.

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/issues/5669

**Comment by chickenlj** [comment]
Also, we need to remove the `default` implementation of onResponse once onMessage gets removed.

**Comment by RojerAlone** [comment]
> I would suggest removing `onMessage` completely in the next version.

The `onMessage` method was added in 2.7.5, the change means to rename `onResponse` method, why removing it ?



> Also, we need to remove the `default` implementation of onResponse once onMessage gets removed.

Got it, the target of this pr is to keep compatible with 2.7.5, and I add a `TODO` on `onMessage` method about changing it to non-default .

**Comment by chickenlj** [comment]
https://github.com/apache/dubbo/pull/5731

**Pull request closed without merging**
