### PR TITLE
fix: tcp connection window size split from stream connection window size

### PR DESCRIPTION
**Pull request by JunJieLiu51520**
## What is the purpose of the change
see issue #14635

## Brief changelog
details can see io.netty.handler.codec.http2.Http2FrameCodec#tryExpandConnectionFlowControlWindow

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by JunJieLiu51520** [comment]
details refer to  io.netty.handler.codec.http2.Http2FrameCodec#tryExpandConnectionFlowControlWindow

**Comment by JunJieLiu51520** [comment]
@AlbumenJ  @guohao

**Comment by oxsean** [comment]
LGTM
Bu the way of reading this configuration has been modified in 3.3 and needs to be changed as well.
https://github.com/apache/dubbo/blob/3.3/dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TriHttp2RemoteFlowController.java#L85

Another question, is this default 64k enough for high throughput application?

**Comment by JunJieLiu51520** [comment]
> LGTM Bu the way of reading this configuration has been modified in 3.3 and needs to be changed as well. https://github.com/apache/dubbo/blob/3.3/dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TriHttp2RemoteFlowController.java#L85
> 
> Another question, is this default 64k enough for high throughput application?

**Comment by JunJieLiu51520** [comment]
> LGTM Bu the way of reading this configuration has been modified in 3.3 and needs to be changed as well. https://github.com/apache/dubbo/blob/3.3/dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TriHttp2RemoteFlowController.java#L85

ok~

> 
> Another question, is this default 64k enough for high throughput application?

**Comment by JunJieLiu51520** [comment]
> LGTM Bu the way of reading this configuration has been modified in 3.3 and needs to be changed as well. https://github.com/apache/dubbo/blob/3.3/dubbo-rpc/dubbo-rpc-triple/src/main/java/org/apache/dubbo/rpc/protocol/tri/TriHttp2RemoteFlowController.java#L85
> 
> Another question, is this default 64k enough for high throughput application?

1. ok~  i will change it on 3.3
2.  normally,  64k is the tcp receive buff‘s default value， i think it’enough and it can  adjust  automatically

**Pull request closed without merging**
