### PR TITLE
fix generic type deserialize bug ( #12257 )

### PR DESCRIPTION
**Pull request by CodePlayer**
fix fastjson2 generic type deserialize failed ( issue #12257 )

### CODE REVIEW

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
Dubbo already use `ContextAutoTypeBeforeHandler` to indicate which classes can be deserialized. SupportAutoType should not be enabled.

**Comment by CodePlayer** [comment]
> Dubbo already use `ContextAutoTypeBeforeHandler` to indicate which classes can be deserialized. SupportAutoType should not be enabled.


@AlbumenJ 
But, it **still has bugs**. Same code, using Hessian2 it works, switch to fastjson2 it goes wrong。

I think, Dubbo should remove `JSONReader.Feature.IgnoreAutoTypeNotMatch`, instead of `JSONReader.Feature.SupportAutoType`.

Because Dubbo is based on **interfaces** and is **strongly typed**, fastjson2 will judge whether the types match, and throw an exception if they do not match.

**Comment by AlbumenJ** [comment]
> > Dubbo already use `ContextAutoTypeBeforeHandler` to indicate which classes can be deserialized. SupportAutoType should not be enabled.
> 
> @AlbumenJ But, it **still has bugs**. Same code, using Hessian2 it works, switch to fastjson2 it goes wrong。
> 
> I think, Dubbo should remove `JSONReader.Feature.IgnoreAutoTypeNotMatch`, instead of `JSONReader.Feature.SupportAutoType`.
> 
> Because Dubbo is based on **interfaces** and is **strongly typed**, fastjson2 will judge whether the types match, and throw an exception if they do not match.

For security purpose, we should check type if match. Otherwise, there may some arbitrary serialization issue.

**Comment by CodePlayer** [comment]
I just tested it.
After I upgraded to fastjson **2.0.32-SNAPSHOT**,  it works fine.

The key reason is that fastjson has a bug.  After my feedback, it has been fixed in the new version.
But, the new version has not yet been officially released.

**Comment by CodePlayer** [comment]
> 

Please note that, `JSONReader.Feature.IgnoreAutoTypeNotMatch` means that the types **can be** mismatched.

**It existed before**.

**Pull request closed without merging**
