### PR TITLE
fix-[#5930] fix the bug of recover 

### PR DESCRIPTION
**Pull request by bigbang555**
## What is the purpose of the change
fix-[#5930]

## Brief changelog
Modify the order of operating memory and ZK in the unregister method

### CODE REVIEW

**Comment by chickenlj** [comment]
I think this is an issue that deserves further investigation.

**Comment by bigbang555** [comment]
it can recur stably in that case which I mention at [#5930]

**Comment by chickenlj** [comment]
Please also check #5959

**Comment by bigbang555** [comment]
yep.I will check it tomorrow.😁

**Comment by chickenlj** [comment]
@bigbang555 Any update on this issue?

**Comment by bigbang555** [comment]
no,I will append in #5959 after check.

**Pull request closed without merging**
