### PR TITLE
[Dubbo-4355] Fix dubbo.jar do not contain "serialization-protobuf-json" module issue

### PR DESCRIPTION
**Pull request by vio-lin**
fix issue #4355
## What is the purpose of the change
 the value of include node in dubbo-all/pom.xml is different from value in module
<include>org.apache.dubbo:dubbo-serialization-protobuf-json</include>

<dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-serialization-protobuf-json</artifactId>
            <scope>compile</scope>
            <optional>true</optional>
  </dependency>

## Brief changelog

 change one node value in dubbo-all/pom.xml 

## Verifying this change

 change one node value in dubbo-all/pom.xml 

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [x] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by htynkn** [comment]
LGTM, CI running now. will merge after CI pass. Close #4355

**Comment by vio-lin** [comment]
Hi all, 
        In this merge, some branch is commit information is not what i want. As  my commit is merged into master but not in Release 2.7.3.If there is any wrong  occurred. Time is 2019.6.21 12:18
图片  
Dubbo-4355 should merged into 2.7.3-release， isn't it。

**Comment by htynkn** [comment]
hey @vio-lin , I have to say sorry for this mistake. 

First this PR should include in 2.7.3 release and thanks very much for your contribution. F
or version 2.7.3, we are not officially in code frenze for this version and also there are many chance to  include it (for example in RC). And this PR is necessary for master branch too. So for this PR, it should go to master branch first and will be pick up into release branch.

So yesterday after I check this PR and click merge button in github, I notice this PR is for release branch, instead of master. I try to cherry-pick your commit to master and push it, but because of the configuration for repo, changes to master must be reviewed so I can't push directly. then I create another PR #4364 to merge it to master. 
I thought in this way, the commit should able to keep your name and include in git history, but after click merge button, github do a squash and overwrite origin author, so the commit information is changed. Really very sorry for this mistake.

And for release branch, I revert it because changes should review and pick up when release process officially start. And I mentioned above, this change will include in 2.7.3 and I already added milestone label yesterday.

Thanks again for your contribution and sorry for this merge issue that changed commit information.

**Comment by vio-lin** [comment]
> hey @vio-lin , I have to say sorry for this mistake.
> 
> First this PR should include in 2.7.3 release and thanks very much for your contribution. F
> or version 2.7.3, we are not officially in code frenze for this version and also there are many chance to include it (for example in RC). And this PR is necessary for master branch too. So for this PR, it should go to master branch first and will be pick up into release branch.
> 
> So yesterday after I check this PR and click merge button in github, I notice this PR is for release branch, instead of master. I try to cherry-pick your commit to master and push it, but because of the configuration for repo, changes to master must be reviewed so I can't push directly. then I create another PR #4364 to merge it to master.
> I thought in this way, the commit should able to keep your name and include in git history, but after click merge button, github do a squash and overwrite origin author, so the commit information is changed. Really very sorry for this mistake.
> 
> And for release branch, I revert it because changes should review and pick up when release process officially start. And I mentioned above, this change will include in 2.7.3 and I already added milestone label yesterday.
> 
> Thanks again for your contribution and sorry for this merge issue that changed commit information.
Hi htynkn ,
Thank you for your message. It is so grateful to receive such a long message with all information I need.
 I think it is ok for me to continue working in branch 2.7.3 release.Thank you.

**Pull request merged**
