### PR TITLE
fix offset always be in [0 leastWeight]

### PR DESCRIPTION
**Pull request by cangmohuyang**
## What is the purpose of the change

XXXXX

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by ralf0131** [comment]
Please describe your issue first.

**Comment by cangmohuyang** [comment]
你好，实际没有遇到问题。从代码上看，会存在这个bug。或者我没有完全理解，烦请给解答一下，代码中怎么避免[0 leastweight]区间，这种情况的。 zhangweitech 邮箱：zhangweitech@gmail.com 签名由 网易邮箱大师 定制 On 07/03/2019 22:42, Huxing Zhang wrote: Please describe your issue first. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ralf0131** [comment]
> 你好，实际没有遇到问题。从代码上看，会存在这个bug。

Please clearly define what the bug is, how to reproduce it, what is the expected result, and what it the actual result. I suggest to create an issue and link to this pull request. This makes the maintainers quickly to know your purpose of your pull request.

I also suggest to add unit tests for your changes.

**Comment by tswstarplanet** [comment]
I check the code and I think you may misunderstand the algorithm

**Comment by beiwei30** [comment]
did we reach the consensus, and can this pull request be either closed or merged?

**Comment by beiwei30** [comment]
i check the original code, the logic is correct.

**Comment by beiwei30** [comment]
image this:

4 and 8
randam: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11

weight 4 will get 0, 1, 2, 3
weight 8 will get 4, 5, 6, 7, 8, 9, 10, 11

so, weight 8 has twice chance to get invoked than weight 4.

**Comment by cangmohuyang** [comment]
Ok。 zhangweitech 邮箱：zhangweitech@gmail.com 签名由 网易邮箱大师 定制 On 07/16/2019 17:53, Ian Luo wrote: image this: 4 and 8 randam: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 weight 4 will get 0, 1, 2, 3 weight 8 will get 4, 5, 6, 7, 8, 9, 10, 11 so, weight 8 has twice chance to get invoked than weight 4. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Pull request closed without merging**
