### PR TITLE
Fix override configMode

### PR DESCRIPTION
**Pull request by BurningCN**
## What is the purpose of the change

follow up #9628

### CODE REVIEW

**Comment by BurningCN** [comment]
@AlbumenJ PTAL

**Comment by CrazyHZM** [comment]
@BurningCN 
Documentation about override config mode is missing, https://github.com/apache/dubbo-website/issues/1297 Would you like to supplement this part of the documentation?

**Review by CrazyHZM — APPROVED** [review]
LGTM

**Comment by BurningCN** [comment]
> @BurningCN Documentation about override config mode is missing, [apache/dubbo-website#1297](https://github.com/apache/dubbo-website/issues/1297) Would you like to supplement this part of the documentation?

OK, sure

**Pull request merged**
