### PR TITLE
De-duplicate the filter returned by the getActivateExtension method

### LINKED ISSUE #7587: dubbo supports duplicate filters which are defined by user，can be optimized?
In dubbo ,it supports  duplicate filters which are defined by user，this situation is normal or can be optimized?
and then i found there is no priority concept in some dubbo configurations 。
It's my opinion above,  can you help me out with any queries?
thanks!

### PR DESCRIPTION
**Pull request by xiaoheng1**
## What is the purpose of the change

De-duplicate the filter returned by the getActivateExtension method

see more detail from fix #7587 

## Verifying this change

- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by AlbumenJ** [comment]
Shall we notify users that there contains two extension have the same name by loggeer?

**Comment by xiaoheng1** [comment]
> Shall we notify users that there contains two extension have the same name by loggeer?

If just print the log, the user also needs to remove it manually, and may also ignore this log.
If the system supports filtering, it will be easier for users to use.

**Comment by AlbumenJ** [comment]
> > Shall we notify users that there contains two extension have the same name by loggeer?
> 
> If just print the log, the user also needs to remove it manually, and may also ignore this log.
> If the system supports filtering, it will be easier for users to use.

Filter those duplicated and log out to notify that has been filtered.

**Comment by xiaoheng1** [comment]
> Filter those duplicated and log out to notify that has been filtered.

Sorry, I misunderstand. Now let’s add a log.

**Pull request merged**
