### PR TITLE
test case about hessian2 反序列化bug #3640

### PR DESCRIPTION
**Pull request by CrazyHZM**
## What is the purpose of the change

test case about hessian2 反序列化bug #3640
Repair in hessian-lite： https://github.com/dubbo/hessian-lite/pull/8

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/incubator-dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/incubator-dubbo/tree/master/dubbo-test).
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/incubator-dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by CrazyHZM** [comment]
Wait for hessian-lite to be repaired and then merged

**Comment by lovepoem** [comment]
How about add the test case to hessian-lite ,then we can verify the change of hessian-lite

**Comment by CrazyHZM** [comment]
> How about add the test case to hessian-lite too , then we can verify the change of hessian-lite


Add later

**Comment by ralf0131** [comment]
The UT are failing. Should we wait for the hessian-lite fix before merge this?

**Comment by CrazyHZM** [comment]
> The UT are failing. Should we wait for the hessian-lite fix before merge this?


Yes, I have submitted pr to fix it, waiting for review

**Comment by ralf0131** [comment]
I just applied the label `status/do-not-merge`, I think it is ready to merge once the UT get passed.

**Comment by CrazyHZM** [comment]
> UT get passed


No problem, after the hessian-lite fix I will let UT pass

**Comment by lovepoem** [comment]
https://github.com/dubbo/hessian-lite/pull/8  is merged

**Comment by CrazyHZM** [comment]
@ralf0131 @lovepoem 
1.Does the hessian-lite project need to be repackaged in order for the UT to pass?
2.Protostuff Serialization seems to have this bug too, I will open a new pr to fix it.  Detailed content can be viewed ci error message .
https://travis-ci.org/apache/incubator-dubbo/jobs/508286988

**Comment by ralf0131** [comment]
I think hessian-lite should publish a new version, and Dubbo should upgrade the version.

**Comment by AlbumenJ** [comment]
@CrazyHZM these ut cases may cause other serializer failed such as protobuf is not support null in list. do you have any ideas?

**Comment by AlbumenJ** [comment]
Close for long time no response.

Please feel free to reopen if you have any question.

If you think these changes still useful in the latest master branch, please submit a new pull request.

**Pull request closed without merging**
