### PR TITLE
[Dubbo-perf]: Reduce object allocation for ProtocolUtils.serviceKey(int, Stri…

### PR DESCRIPTION
**Pull request by LinShunKang**
…ng, String, String)

## What is the purpose of the change

Reduce object allocation and memory copy.

## Brief changelog

Add a cache for `ProtocolUtils.serviceKey(int, String, String, String)`.

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ x Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by LinShunKang** [comment]
@chickenlj PTAL.

**Comment by chickenlj** [comment]
LGTM.

**Comment by chickenlj** [comment]
Please, add LICENSE header for newly added files.

**Comment by chickenlj** [comment]
Sorry for bothering you again, this file needs LICENSE too.

dubbo-common/src/test/java/org/apache/dubbo/rpc/support/ProtocolUtilsTest.java

**Pull request merged**
