### PR TITLE
fix issue 10637， assign provider namespace when call muti providers

### PR DESCRIPTION
**Pull request by niejian**
## What is the purpose of the change
add attribute(providerNamespace) in @DubboReference, that fix issue #10637

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by AlbumenJ** [comment]
@conghuhu PTAL

**Comment by conghuhu** [comment]
image
@niejian 这里也需要加上配置项。

然后需要在[dubbo-website](https://github.com/apache/dubbo-website)中补齐对应的配置项文档

**Comment by niejian** [comment]
@conghuhu 文档已添加说明：https://github.com/apache/dubbo-website/pull/1524

**Comment by conghuhu** [comment]
> @conghuhu 文档已添加说明：[apache/dubbo-website#1524](https://github.com/apache/dubbo-website/pull/1524)

image
这个地方还需要改一下

**Comment by niejian** [comment]
这个已经改了的

https://github.com/apache/dubbo/pull/10671/commits/5c4fcbfede7ef3f89883b90739665de888652544#diff-35b79610cf788e82cea1e388f21c1a79e41cd10b1fc9a687c44a32d2e107e36d

**Comment by niejian** [comment]
> > @conghuhu 文档已添加说明：[apache/dubbo-website#1524](https://github.com/apache/dubbo-website/pull/1524)
> 
> image 这个地方还需要改一下

已经改了

https://github.com/apache/dubbo/commit/5c4fcbfede7ef3f89883b90739665de888652544#diff-35b79610cf788e82cea1e388f21c1a79e41cd10b1fc9a687c44a32d2e107e36d

**Comment by AlbumenJ** [comment]
Please rebase your branch on 3.1. `3.1.1-release` branch is only for release, should not merge in any changes.

**Comment by niejian** [comment]
> Please rebase your branch on 3.1. `3.1.1-release` branch is only for release, should not merge in any changes.

all changes have been commited to branch 3.1

https://github.com/niejian/dubbo/commit/8c6025fbfe95cbbd149f5c1b736d1ab1846cf057

**Comment by AlbumenJ** [comment]
> > Please rebase your branch on 3.1. `3.1.1-release` branch is only for release, should not merge in any changes.
> 
> all changes have been commited to branch 3.1
> 
> [niejian@8c6025f](https://github.com/niejian/dubbo/commit/8c6025fbfe95cbbd149f5c1b736d1ab1846cf057)

Please submit a new PR for it

**Comment by niejian** [comment]
> > > Please rebase your branch on 3.1. `3.1.1-release` branch is only for release, should not merge in any changes.
> > 
> > 
> > all changes have been commited to branch 3.1
> > [niejian@8c6025f](https://github.com/niejian/dubbo/commit/8c6025fbfe95cbbd149f5c1b736d1ab1846cf057)
> 
> Please submit a new PR for it

https://github.com/apache/dubbo/pull/10686

**Comment by niejian** [comment]
#10686

**Pull request closed without merging**
