### PR TITLE
RequestEvent optimization

### PR DESCRIPTION
**Pull request by RapperCL**
## What is the purpose of the change

 [issue](https://github.com/apache/dubbo/issues/12654)

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by songxiaosheng — APPROVED** [review]
LGTM

**Comment by RapperCL** [comment]
> Please resolve conflicts

Well, it's resolved

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
It would be better to rename `requestBeforeEvent` to `requestErrorEvent`

**Comment by RapperCL** [comment]
> It would be better to rename `requestBeforeEvent` to `requestErrorEvent`

I don't think so because this is applied to MetricsClusterFilter to monitor exceptions that occur before executing requests

**Comment by RapperCL** [comment]
> It would be better to rename `requestBeforeEvent` to `requestErrorEvent`



> It would be better to rename `requestBeforeEvent` to `requestErrorEvent`

这个事件关注点在于请求执行之前被中止了，所以我认为requestBeforeEvent比较合适，你觉得呢

**Comment by AlbumenJ** [comment]
> > It would be better to rename `requestBeforeEvent` to `requestErrorEvent`
> 
> > It would be better to rename `requestBeforeEvent` to `requestErrorEvent`
> 
> The focus of this event is that the request was aborted before execution, so I think requestBeforeEvent is more appropriate. Do you think so

However there are only one event in the case

**Comment by RapperCL** [comment]
> > > It would be better to rename `requestBeforeEvent` to `requestErrorEvent`
> > 
> > 
> > > It would be better to rename `requestBeforeEvent` to `requestErrorEvent`
> > 
> > 
> > The focus of this event is that the request was aborted before execution, so I think requestBeforeEvent is more appropriate. Do you think so
> 
> However there are only one event in the case
Oh, sure， I've made the update

**Comment by RapperCL** [comment]
> > > It would be better to rename `requestBeforeEvent` to `requestErrorEvent`
> > 
> > 
> > > It would be better to rename `requestBeforeEvent` to `requestErrorEvent`
> > 
> > 
> > The focus of this event is that the request was aborted before execution, so I think requestBeforeEvent is more appropriate. Do you think so
> 
> However there are only one event in the case

Oh, sure! I've made the update

**Review by AlbumenJ — APPROVED** [review]
@songxiaosheng PTAL

**Pull request merged**
