### PR TITLE
support byte[] PojoUtils

### PR DESCRIPTION
**Pull request by owen200008**
## What is the purpose of the change
support byte[] PojoUtils

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by owen200008** [comment]
transfer the protocalbuffer data to the provider

**Comment by owen200008** [comment]
fastjson no support， it use the base64
later i will try to fix it

**Comment by horizonzy** [comment]
Hi, could you add unit test for this case.

**Comment by owen200008** [comment]
it is no good idea to support byte[] in fastjson
it is no way to cover all case.
when  A -> B use proxy mode  A->proxy->B
the proxy not know the class, so it no way to deal with byte[] in fastjson.

**Comment by horizonzy** [comment]
Hi, could you explain it detaily. I can't fully understand your intentions.

**Comment by owen200008** [comment]
close

**Comment by owen200008** [comment]
when A call B
when we use the generic B interface，the req param must be error when use fastjson and req have byte[]

because use fastjson byte[] will encode by base64 to string
the generic B don't know, so the req param map(bytep] is base64 string)

**Pull request closed without merging**
