### PR TITLE
Bump Maven Wrapper to 3.8.7

### PR DESCRIPTION
**Pull request by sconvent**
## What is the purpose of the change
The used Maven version and Maven Wrapper version are out of date.

## Brief changelog
- Bumping Maven version to 3.8.7
- Using the latest distribution of the Maven Wrapper

All of these changes were made using the recommended way with the following command:
`mvn wrapper:wrapper -Dmaven=3.8.7`

## Verifying this change
Just via CI

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [x] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
Should we download `.mvn/wrapper/maven-wrapper.jar` in runtime instead of source provided?

**Comment by sconvent** [comment]
@AlbumenJ It is best practice to have the `.mvn/wrapper/maven-wrapper.jar` checked in into the repo of the project. And it was updated using the recommended way (as stated in the PR with `mvn wrapper:wrapper -Dmaven=3.8.7)`. That command alone did the updates in this PR. I believe sticking to the recommended setup is a good way unless there are good reasons against it.

**Comment by AlbumenJ** [comment]
> It is best practice to have the .mvn/wrapper/maven-wrapper.jar checked in into the repo of the project. And it was updated using the recommended way (as stated in the PR with mvn wrapper:wrapper -Dmaven=3.8.7). That command alone did the updates in this PR. I believe sticking to the recommended setup is a good way unless there are good reasons against it.

@sconvent 
According to the policy[1] from ASF, any project belongs to ASF should prevent to including any binary files (e.g. jar) in source release. 
BTW, I found a maven wrapper mail thread[2] discussing it with ASF members. It is also explicitly mentioned in the discussion that no binaries can be included in the source code

[1] https://cwiki.apache.org/confluence/display/INCUBATOR/Incubator+Release+Checklist
[2] https://lists.apache.org/thread/rwzlx5l0046rcl4zz92m0q8p3mn1xc6r

**Comment by sconvent** [comment]
@AlbumenJ Ok, now I understand the reasoning much better. Thanks for the explanation!
I removed the jar and re-added it to the `.gitignore` file.
Tested it locally and the jar will be downloaded at compile-time.

**Review by AlbumenJ — APPROVED** [review]
LGTM. Thanks for your contribution.

**Pull request merged**
