### PR TITLE
[Dubbo-4861] WIP: fix stackoverflow of protostuff and other errors

### PR DESCRIPTION
**Pull request by Moriadry**
## What is the purpose of the change

And a test case and fix https://github.com/apache/dubbo/issues/4861

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [x] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by tswstarplanet** [comment]
#3252 your pr and this pr are opposite. I think the two prs are both not the solutions. We should find better solutions.

**Comment by tswstarplanet** [comment]
I think it's a problem of Protostuff project, it should provide a unified util class to process either loop-reference object or non-loop-reference object.

**Comment by Moriadry** [comment]
yes, I also find this problem.

It seems there are something wired about the ProtostuffObjectOutput implement, with this object used, It will cause an endless loop.  I will spend more time digging into it.

**Comment by Moriadry** [comment]
@tswstarplanet When I use protostuff directly, There are no endless loop shown up.  Maybe this is not the problem of Protostuff?

**Comment by tswstarplanet** [comment]
@Moriadry Good! You can oprimize the class

**Comment by beiwei30** [comment]
I am a little bit confused, @Moriadry. What this pull request does is to add more tests, is it sufficient?

**Comment by Moriadry** [comment]
@beiwei30 I caught stackoverflow error when I add two unit tests. And it turns out the Inner class need a `static` declaration , otherwise It will show us SOF error. The current implement of Protostuff project is correct.

Do you think we need to add those two tests in `ProtostuffObjectOutputTest.java`?  If not so, I will close pr and issue.

**Comment by beiwei30** [comment]
> @beiwei30 I caught stackoverflow error when I add two unit tests. And it turns out the Inner class need a `static` declaration , otherwise It will show us SOF error. The current implement of Protostuff project is correct.
> 
> Do you think we need to add those two tests in `ProtostuffObjectOutputTest.java`? If not so, I will close pr and issue.

More test, better. I will merge.

**Pull request merged**
