### PR TITLE
[DUBBO-63] an object MUST equals to itself.

### PR DESCRIPTION
**Pull request by XenoAmess**
## What is the purpose of the change

an object MUST equals to itself.

### CODE REVIEW

**Review by AlbumenJ — APPROVED** [review]
LGTM.

**Comment by XenoAmess** [comment]
@chickenlj this pr can be seen as a bug.
I havn't see people making classes who can have object who can not equals itself.

**Review by chickenlj — APPROVED** [review]
LGTM

**Comment by chickenlj** [comment]
I am merging this patch now.

**Pull request merged**
