### PR TITLE
Fix consumer can not get server attachment info with using explicit-target(#7937)

### PR DESCRIPTION
**Pull request by mr3**
## What is the purpose of the change
Fix issue[#7937]
Revert ConsumerContextFilter
Remove ConsumerContextClusterInterceptor
see https://github.com/apache/dubbo/pull/7986

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by chickenlj** [comment]
I don't think we cannot simply replacing Consumer ClusterInterceptor with Filter. ConsumerContext was a Filter and was changed to a ClusterInterceptor after some careful thinking.

While target server is only a test feature that is not recommended to use in production, I would recommend trying to find other ways to enhance it.

**Comment by chickenlj** [comment]
I will let #7937 open and close this or for it's clearly not suitable.

**Comment by mr3** [comment]
> I don't think we cannot simply replacing Consumer ClusterInterceptor with Filter. ConsumerContext was a Filter and was changed to a ClusterInterceptor after some careful thinking.
> 
> While target server is only a test feature that is not recommended to use in production, I would recommend trying to find other ways to enhance it.

Agree with you. We use explicit-target when replay product traffic in test environment, 

Now we have added it a filter(be activated with parameter) to fix this in the internal verison.

_"after some careful thinking."_  more details?

**Comment by AlbumenJ** [comment]
> > I don't think we cannot simply replacing Consumer ClusterInterceptor with Filter. ConsumerContext was a Filter and was changed to a ClusterInterceptor after some careful thinking.
> > While target server is only a test feature that is not recommended to use in production, I would recommend trying to find other ways to enhance it.
> 
> Agree with you. We use explicit-target when replay product traffic in test environment,
> 
> Now we have added it a filter(be activated with parameter) to fix this in the internal verison.
> _"after some careful thinking."_ more details?

Imaging that there is an invocation invoke failed at the first time and it success in the second time. If we use `ConsumerContext`, the rpc context will be cleared in the first and the second time cannot fetch it due to `RpcContext.removeContext(true);`

**Comment by mr3** [comment]
@AlbumenJ Got it, thanks.

**Pull request closed without merging**
