### PR TITLE
fix reference bean name conflicts

### PR DESCRIPTION
**Pull request by liufeiyu1002**
## What is the purpose of the change

fix reference bean name conflicts 
这个问题之前修复过一次，情况没有考虑全面， 启动顺序不同会导致失败
eg:
```
@DubboReference
private AService aservice;
@DubboReference
private AService bservice;
@DubboReference
private BService bservice;
```
当 `AService` 扫描完成以后, 容器中为

1.  ` beanDefintions("aservice",ABeanDefinitonInfo) `
2.  ` alias ("bservice","aservice")`

扫描`BService` 时 容器中为

1. `BeanDefinitions ("bservice":BDefinitionInfo)` 

因为当扫描`BService`  执行到   ` if (beanDefinitionRegistry.containsBeanDefinition(referenceBeanName))`  这里 `referenceBeanName 值为 bservice ` 会返回false， 且`bservice `是第一次注册会直接注册到 BeanDefinitions 中

此时会出现即注册了 `AService `的alias `bservice` 又注册了 `BService`的 `beanDefinition `的`bservice `，在注入属性时会获取到错误的类型

## Brief changelog
修改判断逻辑 ,同时判断当前 `referenceBeanName `是否在`beanDefinition` 或者是否被注册为别名,

1. 存在 `beanDefinition`中时 执行旧的逻辑
2. `beanDefinition  `中不存在 但是被注册为别名 则从 别名中获取到 原始的 `beanName `来获取`beanDefinition `信息，后续执行和之前一样的重复处理逻辑

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by liufeiyu1002** [comment]
ISSUE [11691](https://github.com/apache/dubbo/issues/11691) [11688](https://github.com/apache/dubbo/issues/11688) [10335](https://github.com/apache/dubbo/issues/10335)  @BurningCN  @AlbumenJ

**Review by AlbumenJ — APPROVED** [review]
LGTM

**Comment by AlbumenJ** [comment]
Would you please add some uts to verify this?

**Comment by AlbumenJ** [comment]
> @DubboReference
> private AService aservice;
> @DubboReference
> private AService bservice;
> @DubboReference
> private BService bservice;

基于这个 case 补一个单测来验证下

**Review by AlbumenJ — APPROVED** [review]

**Comment by linjianming02** [comment]
哈喽，这个问题预计会在哪个版本发布呢？   我现在是3.1.7。 @AlbumenJ

**Comment by huo-feng-ding** [comment]
3.1.7版本还存在使用tri协议kryo序列化时，消费端去调服务端如果传的参数是null，dubbo报异常；看源码已经修复了，但还没发布，看来用新版的人不多呀

**Comment by AlbumenJ** [comment]
> 哈喽，这个问题预计会在哪个版本发布呢？ 我现在是3.1.7。 @AlbumenJ

本周末会发布

**Pull request merged**
