### PR TITLE
ignore zk ut 

### PR DESCRIPTION
**Pull request by chickenlj**

### CODE REVIEW

**Review by codeimport — APPROVED** [review]

**Comment by codeimport** [comment]
2022-01-10T14:06:15.6831451Z [ERROR] ZooKeeper JMX enabled by default
2022-01-10T14:06:15.6848958Z [ERROR] Using config: /home/runner/work/dubbo/dubbo/.tmp/zookeeper/2181/apache-zookeeper-bin/bin/../conf/zoo.cfg
2022-01-10T14:06:16.1270359Z [INFO] 
2022-01-10T14:06:16.1271396Z [INFO] Results:
2022-01-10T14:06:16.1271904Z [INFO] 
2022-01-10T14:06:16.1272563Z [ERROR] Failures: 
2022-01-10T14:06:16.1273617Z [ERROR]   ReferenceConfigTest.test1ReferenceRetry:758 expected: not <null>
2022-01-10T14:06:16.1275204Z [ERROR]   ReferenceConfigTest.test2ReferenceRetry:808 expected: <true> but was: <false>
2022-01-10T14:06:16.1277596Z [ERROR]   MultiInstanceTest.testDefaultConsumerApplication:174 java.lang.IllegalStateException: java.lang.IllegalStateException: zookeeper not connected
2022-01-10T14:06:16.1280020Z java.lang.IllegalStateException: java.lang.IllegalStateException: zookeeper not connected
2022-01-10T14:06:16.1282806Z 	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.prepareEnvironment(DefaultApplicationDeployer.java:665)
2022-01-10T14:06:16.1286608Z 	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.startConfigCenter(DefaultApplicationDeployer.java:258)
2022-01-10T14:06:16.1290299Z 	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.initialize(DefaultApplicationDeployer.java:182)
2022-01-10T14:06:16.1293463Z 	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.start(DefaultApplicationDeployer.java:526)
2022-01-10T14:06:16.1296047Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:224)
2022-01-10T14:06:16.1298208Z 	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:214)
2022-01-10T14:06:16.1301645Z 	at org.apache.dubbo.config.bootstrap.MultiInstanceTest.testDefaultConsumerApplication(MultiInstanceTest.java:171)
2022-01-10T14:06:16.1305476Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-01-10T14:06:16.1307646Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2022-01-10T14:06:16.1310183Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-01-10T14:06:16.1312073Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2022-01-10T14:06:16.1313859Z 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
2022-01-10T14:06:16.1316348Z 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2022-01-10T14:06:16.1327483Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2022-01-10T14:06:16.1330734Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2022-01-10T14:06:16.1335959Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
2022-01-10T14:06:16.1339479Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
2022-01-10T14:06:16.1342636Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2022-01-10T14:06:16.1345483Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2022-01-10T14:06:16.1348598Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2022-01-10T14:06:16.1352093Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2022-01-10T14:06:16.1355846Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2022-01-10T14:06:16.1361004Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2022-01-10T14:06:16.1368821Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2022-01-10T14:06:16.1409088Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2022-01-10T14:06:16.1419202Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
2022-01-10T14:06:16.1428439Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-01-10T14:06:16.1438761Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
2022-01-10T14:06:16.1449983Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
2022-01-10T14:06:16.1454147Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
2022-01-10T14:06:16.1466285Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
2022-01-10T14:06:16.1474063Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-01-10T14:06:16.1481409Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2022-01-10T14:06:16.1486252Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2022-01-10T14:06:16.1494853Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2022-01-10T14:06:16.1500386Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-01-10T14:06:16.1504110Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2022-01-10T14:06:16.1507196Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2022-01-10T14:06:16.1509057Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2022-01-10T14:06:16.1512545Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
2022-01-10T14:06:16.1516969Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
2022-01-10T14:06:16.1520008Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-01-10T14:06:16.1523154Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2022-01-10T14:06:16.1525610Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2022-01-10T14:06:16.1528071Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2022-01-10T14:06:16.1531587Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-01-10T14:06:16.1534928Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2022-01-10T14:06:16.1538010Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2022-01-10T14:06:16.1539844Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2022-01-10T14:06:16.1543345Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
2022-01-10T14:06:16.1547798Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
2022-01-10T14:06:16.1581799Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-01-10T14:06:16.1587454Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
2022-01-10T14:06:16.1594034Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
2022-01-10T14:06:16.1599344Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
2022-01-10T14:06:16.1606444Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2022-01-10T14:06:16.1627762Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
2022-01-10T14:06:16.1635443Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
2022-01-10T14:06:16.1644332Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
2022-01-10T14:06:16.1656328Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2022-01-10T14:06:16.1664750Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
2022-01-10T14:06:16.1671294Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
2022-01-10T14:06:16.1675844Z 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
2022-01-10T14:06:16.1682072Z 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
2022-01-10T14:06:16.1688205Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
2022-01-10T14:06:16.1692823Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
2022-01-10T14:06:16.1698970Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
2022-01-10T14:06:16.1707231Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
2022-01-10T14:06:16.1714009Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
2022-01-10T14:06:16.1719826Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
2022-01-10T14:06:16.1723427Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
2022-01-10T14:06:16.1726074Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
2022-01-10T14:06:16.1730322Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
2022-01-10T14:06:16.1732002Z Caused by: java.lang.IllegalStateException: zookeeper not connected
2022-01-10T14:06:16.1734079Z 	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:88)
2022-01-10T14:06:16.1740691Z 	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperTransporter.createZookeeperClient(CuratorZookeeperTransporter.java:26)
2022-01-10T14:06:16.1749441Z 	at org.apache.dubbo.remoting.zookeeper.AbstractZookeeperTransporter.connect(AbstractZookeeperTransporter.java:69)
2022-01-10T14:06:16.1760351Z 	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfiguration.<init>(ZookeeperDynamicConfiguration.java:63)
2022-01-10T14:06:16.1771975Z 	at org.apache.dubbo.configcenter.support.zookeeper.ZookeeperDynamicConfigurationFactory.createDynamicConfiguration(ZookeeperDynamicConfigurationFactory.java:47)
2022-01-10T14:06:16.1787651Z 	at org.apache.dubbo.common.config.configcenter.AbstractDynamicConfigurationFactory.lambda$getDynamicConfiguration$0(AbstractDynamicConfigurationFactory.java:39)
2022-01-10T14:06:16.1795991Z 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
2022-01-10T14:06:16.1807236Z 	at org.apache.dubbo.common.config.configcenter.AbstractDynamicConfigurationFactory.getDynamicConfiguration(AbstractDynamicConfigurationFactory.java:39)
2022-01-10T14:06:16.1819134Z 	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.getDynamicConfiguration(DefaultApplicationDeployer.java:702)
2022-01-10T14:06:16.1828551Z 	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.prepareEnvironment(DefaultApplicationDeployer.java:658)
2022-01-10T14:06:16.1834199Z 	... 72 more
2022-01-10T14:06:16.1836616Z Caused by: java.lang.IllegalStateException: zookeeper not connected
2022-01-10T14:06:16.1841654Z 	at org.apache.dubbo.remoting.zookeeper.curator.CuratorZookeeperClient.<init>(CuratorZookeeperClient.java:84)
2022-01-10T14:06:16.1846942Z 	... 81 more
2022-01-10T14:06:16.1847401Z  ==> expected: <true> but was: <false>
2022-01-10T14:06:16.1849570Z [ERROR] Errors: 
2022-01-10T14:06:16.1853143Z [ERROR]   ReferenceConfigTest.testAppendConfig:252 » IllegalState java.lang.IllegalState...
2022-01-10T14:06:16.1855203Z [ERROR]   ReferenceConfigTest.testCreateInvokerForRemoteRefer:530 » Runtime Can not crea...
2022-01-10T14:06:16.1857802Z [ERROR]   ReferenceConfigTest.testCreateInvokerWithRegistryUrlForRemoteRefer:612 » Runtime
2022-01-10T14:06:16.1861815Z [ERROR]   ReferenceConfigTest.testDifferentClassLoader:962 » Runtime Can not create regi...
2022-01-10T14:06:16.1867107Z [ERROR]   ReferenceConfigTest.testMultipleRegistryForRemoteRefer:664 » Runtime Can not c...
2022-01-10T14:06:16.1874053Z [ERROR]   DubboBootstrapTest.testBootstrapStart:244 » IllegalState java.lang.IllegalStat...
2022-01-10T14:06:16.1879082Z [ERROR]   DubboBootstrapTest.testLocalMetadataServiceExporter:275 » IllegalState java.la...
2022-01-10T14:06:16.1883484Z [ERROR]   DubboBootstrapTest.testRemoteMetadataServiceExporter:317 » IllegalState zookee...
2022-01-10T14:06:16.1889065Z [ERROR]   MultiInstanceTest.testAsyncExportAndReferServices:805 » IllegalState java.lang...
2022-01-10T14:06:16.1895059Z [ERROR]   MultiInstanceTest.testBothStartByModuleAndByApplication:603 » IllegalState jav...
2022-01-10T14:06:16.1901254Z [ERROR]   MultiInstanceTest.testBothStartModuleAndApplicationNoWait:685 » IllegalState j...
2022-01-10T14:06:16.1907095Z [ERROR]   MultiInstanceTest.testDefaultMixedApplication:189 » IllegalState java.lang.Ill...
2022-01-10T14:06:16.1912564Z [ERROR]   MultiInstanceTest.testDefaultProviderApplication:159 » IllegalState java.lang....
2022-01-10T14:06:16.1916961Z [ERROR]   MultiInstanceTest.testIsolatedApplications:141 » IllegalState java.lang.Illega...
2022-01-10T14:06:16.1921535Z [ERROR]   MultiInstanceTest.testMultiModuleApplication:272 » IllegalState java.lang.Ille...
2022-01-10T14:06:16.1925071Z [ERROR]   MultiInstanceTest.testMultiModuleDeployAndReload:469 » IllegalState java.lang....
2022-01-10T14:06:16.1929747Z [ERROR]   MultiInstanceTest.testMultiProviderApplicationsStopOneByOne:336 » IllegalState
2022-01-10T14:06:16.1933704Z [ERROR]   MultiInstanceTest.testOldApiDeploy:730 » Runtime Can not create registry servi...
2022-01-10T14:06:16.1936767Z [ERROR]   MultiInstanceTest.testSharedApplications:211 » IllegalState java.lang.IllegalS...
2022-01-10T14:06:16.1939875Z [ERROR]   MultipleRegistryCenterExportMetadataIntegrationTest.integrate:132 » IllegalState
2022-01-10T14:06:16.1942522Z [ERROR]   MultipleRegistryCenterExportProviderIntegrationTest.integrate:159 » IllegalState
2022-01-10T14:06:16.1944969Z [ERROR]   MultipleRegistryCenterInjvmIntegrationTest.integrate:131 » IllegalState java.l...
2022-01-10T14:06:16.1947764Z [ERROR]   MultipleRegistryCenterServiceDiscoveryRegistryIntegrationTest.integrate:150 » IllegalState
2022-01-10T14:06:16.1950639Z [ERROR]   SingleRegistryCenterDubboProtocolIntegrationTest.integrate:126 » IllegalState ...
2022-01-10T14:06:16.1953176Z [ERROR]   SingleRegistryCenterExportMetadataIntegrationTest.integrate:131 » IllegalState
2022-01-10T14:06:16.1955777Z [ERROR]   SingleRegistryCenterExportProviderIntegrationTest.integrate:164 » IllegalState
2022-01-10T14:06:16.1959010Z [ERROR]   SingleRegistryCenterInjvmIntegrationTest.integrate:131 » IllegalState java.lan...
2022-01-10T14:06:16.1960230Z [INFO] 
2022-01-10T14:06:16.1960734Z [ERROR] Tests run: 628, Failures: 3, Errors: 27, Skipped: 3

**Comment by codeimport** [comment]
I tried to disable the wrong test cases, but other test cases related to ZK also failed in jdk17. By checking the log, I found that the problem unit test were caused by using ZK.

**Comment by codeimport** [comment]
Maybe The ZK version used by dubbo3.0 does have compatibility problems under jdk17.  May be remove the workflow of jdk17 until ZK officially fixes this problem is a good idea?
@chickenlj

**Comment by chickenlj** [comment]
Yes, you are right. It is because of the client version not compatible with JDK 17.

**Pull request closed without merging**
