### PR TITLE
fix bug https://github.com/apache/dubbo/issues/11644

### PR DESCRIPTION
**Pull request by wegod**
## What is the purpose of the change

fix bug see https://github.com/apache/dubbo/issues/11644

## Brief changelog

Add compatible method of com.alibaba.dubbo.rpc.Result and com.alibaba.dubbo.rpc.Invoker

## Verifying this change

I test calling 2.6.x's method both sync and async

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by AlbumenJ — CHANGES_REQUESTED** [review]
Please change the target branch to `3.1`. 2.7.x will EOL in this month.

**Comment by wegod** [comment]
> Please change the target branch to `3.1`. 2.7.x will EOL in this month.

We have many projects using dubbo, it's hard to push migrate to 3.x. We want to migrate to 2.7.x first.
Please consider merge to 2.7.x first, thanks

**Comment by AlbumenJ** [comment]
> > Please change the target branch to `3.1`. 2.7.x will EOL in this month.
> 
> We have many projects using dubbo, it's hard to push migrate to 3.x. We want to migrate to 2.7.x first. Please consider merge to 2.7.x first, thanks

The 2.7.x branch will not have any new releases, so you won't be able to use it even if it is merged.

**Comment by wegod** [comment]
> The 2.7.x branch will not have any new releases, so you won't be able to use it even if it is merged.

Well, I changed the target branch to 3.1

**Pull request closed without merging**
