### PR TITLE
[Dubbo-4674]make multiple reference to service effect

### LINKED ISSUE #4674: Multiple @Reference annotations only have one effect
- [√] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [√] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.3
* Operating System version: Windows 10
* Java version: Oracle JDK 1.8

### Steps to reproduce this issue

1. Inject a DubboService into a spring bean with @Reference(async = true)
2. Inject the same DubboService into another spring bean with @Reference(async = false)
3. Invoke the methods in these two beans

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

One bean is an asynchronous call and the other is a synchronous call

### Actual Result

They are all asynchronous or synchronous

```
@Component("demoServiceComponent")
public class DemoServiceComponent implements DemoService {

    @Reference(async = true)
    private DemoService demoService;

    @Override
    public String sayHello(String name) {
        return demoService.sayHello(name);
    }
}

@Service("helloService")
public class HelloService {

    @Reference(async = false)
    private DemoService demoService;

    public String sayHello(String name) {
        return demoService.sayHello(name);
    }
}

public static void main(String[] args) {
    AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext(ConsumerConfiguration.class);
    context.start();
    DemoService service = context.getBean("demoServiceComponent", DemoServiceComponent.class);
    HelloService helloService = context.getBean("helloService", HelloService.class);
    System.out.println("result : " + service.sayHello("sync"));
    System.out.println("result : " + helloService.sayHello("async"));
}
```

### PR DESCRIPTION
**Pull request by tswstarplanet**
## What is the purpose of the change

fix #4674

## Brief changelog

main:
ReferenceAnnotationBeanPostProcessor.java
test:
EnableDubboTest.java
DemoServiceImpl.java

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by tswstarplanet** [comment]
I find the solution has a problem. I will have a look again.

**Comment by tswstarplanet** [comment]
> I find the solution has a problem. I will have a look again.

I think it has been solved.

**Comment by tswstarplanet** [comment]
@mercyblitz Would you please review this pr ?

**Comment by AlbumenJ** [comment]
@tswstarplanet pls resolve conflicts with the latest master branch

**Comment by AlbumenJ** [comment]
Close for long time no response.
Please feel free to reopen if you have any question.

**Pull request closed without merging**
