### PR TITLE
fix When the exception handling class cannot be obtained, it should recursively search the base class(#12245)

### PR DESCRIPTION
**Pull request by iqinning**
…recursively search the base class (#12245)

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [x] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by AlbumenJ — COMMENTED** [review]
@suncairong163 PTAL

**Review by AlbumenJ — APPROVED** [review]

**Comment by suncairong163** [comment]
ExceptionHandler的功能是来自于spring的controllerAdvice和restEasy的ExceptionMapper,这两者都是对某一个具体类型的Exception做处理的，我看这个更改逻辑是为了向上查找super的ExceptionHandler,就不是某种具体类型的处理了，

**Comment by iqinning** [comment]
> ExceptionHandler的功能是来自于spring的controllerAdvice和restEasy的ExceptionMapper,这两者都是对某一个具体类型的Exception做处理的，我看这个更改逻辑是为了向上查找super的ExceptionHandler,就不是某种具体类型的处理了，

据我了解，不管是 spring mvc 的异常处理器查找机制，还是rest easy 都是往基类查找的以下是 rest-easy 处理代码

```

/**
    * Execute an ExceptionMapper if one exists for the given exception.  Recurse to base class if not found
    *
    * @param exception
    * @return true if an ExceptionMapper was found and executed
    */
   @SuppressWarnings(value = "unchecked")
   public Response executeExceptionMapper(Throwable exception)
   {
      ExceptionMapper mapper = null;

      Class causeClass = exception.getClass();
      while (mapper == null) {
         if (causeClass == null) break;
         mapper = providerFactory.getExceptionMappers().get(causeClass);
         if (mapper == null) causeClass = causeClass.getSuperclass();
      }
      if (mapper != null) {
         mapperExecuted = true;
         Response jaxrsResponse = mapper.toResponse(exception);
         if (jaxrsResponse == null) {
            jaxrsResponse = Response.status(204).build();
         }
         return jaxrsResponse;
      }
      return null;
   }

```

**Comment by suncairong163** [comment]
ok，那就没问题了

**Pull request merged**
