### PR TITLE
fix attachments override

### PR DESCRIPTION
**Pull request by chickenlj**

### CODE REVIEW

**Comment by qinliujie** [comment]
LGTM

**Comment by AlbumenJ** [comment]
@chickenlj  

image

Hi, please remove unused import in `dubbo-remoting/dubbo-remoting-api/src/main/java/org/apache/dubbo/remoting/api/Connection.java`

**Comment by chickenlj** [comment]
Thanks for reminding, done.

**Review by AlbumenJ — APPROVED** [review]
LGTM.

**Pull request merged**
