### PR TITLE
Remove the thread parameters copied from the provider

### LINKED ISSUE #13291: Triple协议 consumer端线程池线程数依赖于provider端配置
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.7
* Java version: 8

### Steps to reproduce this issue
构造一个Consumer，一个Provider端
1. Provider端只提供triple协议，线程池大小为1200。
image
具体的接口级注册中心的信息如下：side=provider，threads=1200
image
2. 重新部署下Consumer，进行多次调用
3. 在org.apache.dubbo.rpc.protocol.tri.TripleInvoker 类中打断点，debug查看streamExecutor，可以看到核心线程数为1200.
image

追踪代码的话，可以从org.apache.dubbo.common.threadpool.manager.DefaultExecutorRepository#createExecutorIfAbsent中看，线程池是根据url创建出来的。
image

更内部的线程池参数，org.apache.dubbo.common.threadpool.support.fixed.FixedThreadPool，是从url的threads参数获取的。
image

这就引申出一个问题：Consumer端的这个线程池，核心线程数是依赖于Provider端url配置的。
Provider端面临的场景和Consumer端可能不同，机器配置、数量上都可能不相同。Provider对自己这边配置的合理线程数，对Consumer这一端可能就不合理了。
我们这边使用的时候，可能会存在OOM风险。

### PR DESCRIPTION
**Pull request by finefuture**
## What is the purpose of the change
Fix #13291 

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by AlbumenJ** [comment]
It would be better to provide a more flexible way to customize the parameters registered to the registry. Such as `methods` key is useless now and will takes a lot storage.

**Comment by EarthChen** [comment]
> It would be better to provide a more flexible way to customize the parameters registered to the registry. Such as `methods` key is useless now and will takes a lot of storage.

I think this can be done for the time being and we will see how to optimize it later.

**Review by EarthChen — APPROVED** [review]
LGTM

**Comment by finefuture** [comment]
> It would be better to provide a more flexible way to customize the parameters registered to the registry. Such as `methods` key is useless now and will takes a lot of storage.

Make good sense, I will give it a try.

**Comment by finefuture** [comment]
Fixed in #13304

**Pull request closed without merging**
