### PR TITLE
change alibaba_spring_context_support_version to 1.0.11

### LINKED ISSUE #7797: Dubbo 2.7.5, 2.7.9, 2.7.11, 2.7.12 are incompatiable with nacos-spring-context 1.1.0
### Environment

* Dubbo version: 2.7.5 or 2.7.9 or 2.7.11 or 2.7.12
* Operating System version: centos7
* Java version: 1.8
* nacos-spring-context 1.1.0

### Steps to reproduce this issue
create a maven spring-boot test application which pom.xml has dubbo first and nacos-spring-context 1.1.0 later,  
with dubbo which depend on spring-context-support 1.0.10:
a ClassCastException - com.sun.proxy.$Proxy...NNN... cannot be cast to java.util.Map - will be throwed at AnnotationNacosInjectedBeanPostProcessor.java line 145.
with dubbo which depend on spring-context-support 1.0.8 or less:
An attempt was made to call a method that does not exist (com.alibaba.spring.util.BeanUtils.getBeanNames)

The reason is nacos-spring-context 1.1.0 depends  on spring-context-support 1.0.11 which isn't compliant with that dubbo depends now.

### PR DESCRIPTION
**Pull request by zrlw**
## What is the purpose of the change
1. change alibaba spring-context-support version of dubbo pom.xml to 1.0.11
2. set classValuesAsString and nestedAnnotationsAsMap attributes of ReferenceAnnotationBeanPostProcessor to false
fix #7797

### CODE REVIEW

**Comment by zrlw** [comment]
@horizonzy

**Comment by gang0713** [comment]
这问题啥时候能解决。

**Comment by kylixs** [comment]
@zrlw  Since dubbo 3.0.0, the `AbstractAnnotationBeanPostProcessor` of alibaba `spring-context-support` is no longer used, and this problem should not occur, please check it again. 
Furthermore, dubbo 3 will gradually remove alibaba spring-context-support.

**Comment by wuwen5** [comment]
#7274

**Pull request merged**
