### PR TITLE
fix spelling typo

### LINKED ISSUE #14809: Spelling typo "Excepted context" in file "MetadataServiceNameMapping.java"
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

Dubbo 3.2、dubbo 3.3、dubbo 3.4

### Steps to reproduce this issue

just review the code

### What you expected to happen

```java
if (!succeeded) {
                        int waitTime = ThreadLocalRandom.current().nextInt(casRetryWaitTime);
                        logger.info("Failed to publish service name mapping to metadata center by cas operation. "
                                + "Times: "
                                + currentRetryTimes + ". " + "Next retry delay: "
                                + waitTime + ". " + "Service Interface: "
                                + serviceInterface + ". " + "Origin Content: "
                                + oldConfigContent + ". " + "Ticket: "
                                + configItem.getTicket() + ". " + "Excepted context: "
                                + newConfigContent);
                        Thread.sleep(waitTime);
                    }
```

Considering the context, “Excepted context” should be "Expected Content"。

### Anything else

_No response_

### Are you willing to submit a pull request to fix on your own?

- [X] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by wsliliang**
fix #14809

### CODE REVIEW

**Comment by heliang666s** [comment]
Thank you for your first contribution! Now the CI error is due to something wrong with the community upgrading the Zookeeper version, which has now been fixed, and you can start a new commit and run the CI test again.

**Comment by heliang666s** [comment]
LGTM

**Comment by wsliliang** [comment]
@heliang666s  hi, thanks for your review, but I have nothing to commit any more, is it necessory to run the CI test again?  if it is , how can I run it again without a new commit?

**Comment by heliang666s** [comment]
you can try Merge branch '3.3' into ‘3.3’ or push an empty commit. @wsliliang

**Comment by wsliliang** [comment]
@heliang666s thank you I tried but CI test still not success

**Comment by heliang666s** [comment]
Judging from the error logs, this may be because there are other PRs running CI tests as well, which is causing the port to be occupied. You can wait a little longer and try again. @wsliliang

**Pull request merged**
