### PR TITLE
[Dubbo-5479]fix generic reference does not implements real Interface

### LINKED ISSUE #5479: 当设置泛化调用时，consumer生成的代理类没有实现应用的接口
* 启动provider

dubbo-demo-api-provider

* 启动consumer

dubbo-demo-api-consumer

consumer设置generic

```java
    public static void main(String[] args) {
        ReferenceConfig<DemoService> reference = new ReferenceConfig<>();
        reference.setApplication(new ApplicationConfig("dubbo-demo-api-consumer"));
        reference.setRegistry(new RegistryConfig("zookeeper://127.0.0.1:2181"));
        reference.setInterface(DemoService.class);
        reference.setGeneric(true);
        
        Object obj = reference.get();
        for(Class c : obj.getClass().getInterfaces()) {
            System.err.println(c);
        }
        DemoService service = reference.get();
        String message = service.sayHello("dubbo");
        System.out.println(message);
    }
```

客户端会报错：

```
Exception in thread "main" java.lang.ClassCastException: org.apache.dubbo.common.bytecode.proxy0 cannot be cast to org.apache.dubbo.demo.DemoService
	at org.apache.dubbo.demo.consumer.Application.main(Application.java:42)
```

### PR DESCRIPTION
**Pull request by tswstarplanet**
## What is the purpose of the change

fix #5479

## Brief changelog

XXXXX

## Verifying this change

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `[Dubbo-XXX] Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Run `mvn clean install -DskipTests=false` & `mvn clean test-compile failsafe:integration-test` to make sure unit-test and integration-test pass.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by lzf971107** [comment]
@tswstarplanet 
Hello, your unit test failed.

[ERROR] Failures: 
[ERROR]   ReferenceConfigTest.testReferenceRetry:115 expected: false but was: true

**Comment by tswstarplanet** [comment]
> @tswstarplanet
> Hello, your unit test failed.
> 
> [ERROR] Failures:
> [ERROR] ReferenceConfigTest.testReferenceRetry:115 expected: false but was: true

Yes, I debugged on my computer. I found it is because of the cache file. So I add a piece of code to the unit test method to delete the cache file. It works well on my computer. I don't know why it is not ok on github.

**Comment by lzf971107** [comment]
I pulled your code to my local machine, and after running the unit tests, it is consistent with the github answer. 

Maybe you forgot to modify
https://github.com/apache/dubbo/blob/509d0ae44d944d4bbaa92b018a354673f239e9ee/dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java#L115

https://github.com/apache/dubbo/blob/509d0ae44d944d4bbaa92b018a354673f239e9ee/dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java#L116

```java
        Assertions.assertTrue(success);
        Assertions.assertNotNull(demoService);
```

**Comment by tswstarplanet** [comment]
> > > @tswstarplanet
> > > Hello, your unit test failed.
> > > [ERROR] Failures:
> > > [ERROR] ReferenceConfigTest.testReferenceRetry:115 expected: false but was: true
> > 
> > 
> > Yes, I debugged on my computer. I found it is because of the cache file. So I add a piece of code to the unit test method to delete the cache file. It works well on my computer. I don't know why it is not ok on github.
> 
> I pulled your code to my local machine, and after running the unit tests, it is consistent with the github answer.
> 
> Maybe you forgot to modify
> https://github.com/tswstarplanet/dubbo/blob/509d0ae44d944d4bbaa92b018a354673f239e9ee/dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java#L115
> 
> https://github.com/tswstarplanet/dubbo/blob/509d0ae44d944d4bbaa92b018a354673f239e9ee/dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java#L116
> 
> ```java
>         Assertions.assertTrue(success);
>         Assertions.assertNotNull(demoService);
> ```

No, we should not modify the code like that just to pass the assertion.

**Comment by lzf971107** [comment]
> > > > @tswstarplanet
> > > > Hello, your unit test failed.
> > > > [ERROR] Failures:
> > > > [ERROR] ReferenceConfigTest.testReferenceRetry:115 expected: false but was: true
> > > 
> > > 
> > > Yes, I debugged on my computer. I found it is because of the cache file. So I add a piece of code to the unit test method to delete the cache file. It works well on my computer. I don't know why it is not ok on github.
> > 
> > 
> > I pulled your code to my local machine, and after running the unit tests, it is consistent with the github answer.
> > Maybe you forgot to modify
> > https://github.com/tswstarplanet/dubbo/blob/509d0ae44d944d4bbaa92b018a354673f239e9ee/dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java#L115
> > https://github.com/tswstarplanet/dubbo/blob/509d0ae44d944d4bbaa92b018a354673f239e9ee/dubbo-config/dubbo-config-api/src/test/java/org/apache/dubbo/config/ReferenceConfigTest.java#L116
> > ```java
> >         Assertions.assertTrue(success);
> >         Assertions.assertNotNull(demoService);
> > ```
> 
> No, we should not modify the code like that just to pass the assertion.

Very weird, sometimes success and sometimes failure on my machine.

**Comment by tswstarplanet** [comment]
I know the reason. When we use a Reference to subscribe a service without setting a specified protocol, it will subscribe a Service with any type of Protocol. And the other unit tests may cache service locally. And the failed test will get it.

**Comment by tswstarplanet** [comment]
Why does the added mockprotocol3 cause ClassNotFoundException ?

**Comment by chickenlj** [comment]
Thanks, fixed by another patch #5481. Please help to review if you got time.

**Pull request closed without merging**
