### PR TITLE
optimize: example add Triple protocol Demo

### PR DESCRIPTION
**Pull request by a364176773**
## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Review by guohao — CHANGES_REQUESTED** [review]
Just need add some invoking code in `org.apache.dubbo.demo.consumer.Application`

**Comment by a364176773** [comment]
> Just need add some invoking code in `org.apache.dubbo.demo.consumer.Application`

done

**Comment by guohao** [comment]
`dubbo-rpc-triple` dependency is needed for both consumer and provider's `pom.xml`

**Review by EarthChen — CHANGES_REQUESTED** [review]
- add provider & consumer  dependency `dubbo-rpc-triple`
- change provider register type `<dubbo:registry id="registry1" address="zookeeper://127.0.0.1:2181"/>`

**Comment by a364176773** [comment]
> * add provider & consumer  dependency `dubbo-rpc-triple`
> * change provider register type `<dubbo:registry id="registry1" address="zookeeper://127.0.0.1:2181"/>`

done

**Comment by a364176773** [comment]
> `dubbo-rpc-triple` dependency is needed for both consumer and provider's `pom.xml`

done
image

**Comment by guohao** [comment]
This PR will be merged after figuring out why application service discovery did not work for triple service, plz wait a second

**Comment by a364176773** [comment]
> This PR will be merged after figuring out why application service discovery did not work for triple service, plz wait a second

ok,thx

**Review by xiaoheng1 — APPROVED** [review]
LGTM

**Pull request merged**
