### PR TITLE
remove spring default qos-enable

### LINKED ISSUE #12779: 通过外部配置文件的“dubbo.application.qos-enable=false”配置来关闭QOS不生效
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.2.4
* Operating System version: win10
* Java version: 17

### Steps to reproduce this issue

1. 启动dubbo服务时加入JVM参数：-Ddubbo.properties.file=/data/dubbo/dubbo.properties
2. /data/dubbo/dubbo.properties 中配置：dubbo.application.qos-enable=false
3. 检查 QOS端口是否打开（已打开）
4. 通过监控地址：http://localhost:9002/actuator/dubbo/properties
 查看 qos-enable 属性（true）
```
{
	"dubbo.application.name": "hp-demo-infra-service",
	"dubbo.application.organization": "HP-Socket",
	"dubbo.application.owner": "Kingfisher",
	"dubbo.application.qos-enable": "true",
	"dubbo.application.qos-port": "7002",
	"dubbo.application.version": "0.0.1-SNAPSHOT",
	"dubbo.config.multiple": "true",
	"dubbo.properties.file": "/data/dubbo/dubbo.properties",
	"dubbo.protocol.name": "dubbo",
	"dubbo.protocol.port": "6002",
	"dubbo.registry.file": "/data/dubbo/.cache/dubbo-registry_hp-demo-infra-service.properties",
	"dubbo.resolve.file": "/data/dubbo/dubbo-resolve.properties",
	"dubbo.scan.base-packages": "com.github.hpsocket.demo"
}
```

而通过JVM参数：“-Ddubbo.application.qos-enable=false”，或在 application.yml 中定义 ”dubbo.application.qos-enable: false”，配置是生效的。

### PR DESCRIPTION
**Pull request by xixingya**
## What is the purpose of the change

fix #12779

## Checklist
- [x] Make sure there is a [GitHub_issue](https://github.com/apache/dubbo/issues) field for the change (usually before you start working on it). Trivial changes like typos do not require a GitHub issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Check if is necessary to patch to Dubbo 3 if you are work on Dubbo 2.7
- [ ] Write necessary unit-test to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add sample in [dubbo samples](https://github.com/apache/dubbo-samples) project.
- [ ] Add some description to [dubbo-website](https://github.com/apache/dubbo-website) project if you are requesting to add a feature.
- [ ] GitHub Actions works fine on your own branch.
- [ ] If this contribution is large, please follow the [Software Donation Guide](https://github.com/apache/dubbo/wiki/Software-donation-guide).

### CODE REVIEW

**Comment by xixingya** [comment]
fix https://github.com/apache/dubbo/issues/12779 make this propertis load first so that spring boot config default will not configed

**Comment by AlbumenJ** [comment]
In order to fix #12779, we should remove the hard code of `qos-enable=true` when parsing spring proeprties.

**Comment by xixingya** [comment]
> In order to fix #12779, we should remove the hard code of `qos-enable=true` when parsing spring proeprties.

But where can we set default true value when user doesn't set qos-enable

**Comment by xixingya** [comment]
> In order to fix #12779, we should remove the hard code of `qos-enable=true` when parsing spring proeprties.

if we let dubbo.properties load before application.yml，the default value will not set

**Comment by AlbumenJ** [comment]
> > In order to fix #12779, we should remove the hard code of `qos-enable=true` when parsing spring proeprties.
> 
> if we let dubbo.properties load before application.yml，the default value will not set

This is a breaking change, and if it can only fix `qos-enable` is not worthable. We should fix it in `application.yml`.

**Comment by AlbumenJ** [comment]
org.apache.dubbo.spring.boot.env.DubboDefaultPropertiesEnvironmentPostProcessor#createDefaultProperties

**Comment by xixingya** [comment]
but the other  spring default props also not valid in dubbo.properties  such as dubbo.config.multiple, because the application.yml is load before dubbo.properties @AlbumenJ

**Comment by AlbumenJ** [comment]
image
Please also fix test cases

**Comment by AlbumenJ** [comment]
image

**Review by chickenlj — APPROVED** [review]
LGTM.

**Pull request merged**
